
export type LibraryBook = {
    id: string;
    title: string;
    author: string;
    coverUrl: string;
    url: string;
};

// All books are from Project Gutenberg (public domain)
// URLs point to the plain text files for in-app reading.
export const LIBRARY_BOOKS: LibraryBook[] = [
    {
        id: '84',
        title: 'Frankenstein',
        author: 'Mary Shelley',
        coverUrl: 'https://picsum.photos/300/400?random=11',
        url: 'https://www.gutenberg.org/files/84/84-0.txt',
    },
    {
        id: '2701',
        title: 'Moby Dick; or, The Whale',
        author: 'Herman Melville',
        coverUrl: 'https://picsum.photos/300/400?random=4',
        url: 'https://www.gutenberg.org/files/2701/2701-0.txt',
    },
    {
        id: '1661',
        title: 'The Adventures of Sherlock Holmes',
        author: 'Arthur Conan Doyle',
        coverUrl: 'https://picsum.photos/300/400?random=1',
        url: 'https://www.gutenberg.org/files/1661/1661-0.txt'
    },
    {
        id: '1342',
        title: 'Pride and Prejudice',
        author: 'Jane Austen',
        coverUrl: 'https://picsum.photos/300/400?random=10',
        url: 'https://www.gutenberg.org/files/1342/1342-0.txt',
    },
    {
        id: '345',
        title: 'Dracula',
        author: 'Bram Stoker',
        coverUrl: 'https://picsum.photos/300/400?random=12',
        url: 'https://www.gutenberg.org/files/345/345-0.txt',
    },
    {
        id: '98',
        title: 'A Tale of Two Cities',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=13',
        url: 'https://www.gutenberg.org/files/98/98-0.txt',
    },
    {
        id: '74',
        title: 'The Adventures of Tom Sawyer',
        author: 'Mark Twain',
        coverUrl: 'https://picsum.photos/300/400?random=14',
        url: 'https://www.gutenberg.org/files/74/74-0.txt',
    },
    {
        id: '174',
        title: 'The Picture of Dorian Gray',
        author: 'Oscar Wilde',
        coverUrl: 'https://picsum.photos/300/400?random=15',
        url: 'https://www.gutenberg.org/files/174/174-0.txt',
    },
    {
        id: '11',
        title: 'Alice\'s Adventures in Wonderland',
        author: 'Lewis Carroll',
        coverUrl: 'https://picsum.photos/300/400?random=6',
        url: 'https://www.gutenberg.org/files/11/11-0.txt'
    },
    {
        id: '5200',
        title: 'Metamorphosis',
        author: 'Franz Kafka',
        coverUrl: 'https://picsum.photos/300/400?random=17',
        url: 'https://www.gutenberg.org/files/5200/5200-0.txt',
    },
    {
        id: '4300',
        title: 'Ulysses',
        author: 'James Joyce',
        coverUrl: 'https://picsum.photos/300/400?random=18',
        url: 'https://www.gutenberg.org/files/4300/4300-0.txt',
    },
    {
        id: '2600',
        title: 'War and Peace',
        author: 'Leo Tolstoy',
        coverUrl: 'https://picsum.photos/300/400?random=19',
        url: 'https://www.gutenberg.org/files/2600/2600-0.txt',
    },
    {
        id: '996',
        title: 'Don Quixote',
        author: 'Miguel de Cervantes',
        coverUrl: 'https://picsum.photos/300/400?random=20',
        url: 'https://www.gutenberg.org/files/996/996-0.txt',
    },
    {
        id: '120',
        title: 'Treasure Island',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=21',
        url: 'https://www.gutenberg.org/files/120/120-0.txt',
    },
    {
        id: '1260',
        title: 'Jane Eyre',
        author: 'Charlotte Brontë',
        coverUrl: 'https://picsum.photos/300/400?random=22',
        url: 'https://www.gutenberg.org/files/1260/1260-0.txt',
    },
    {
        id: '768',
        title: 'Wuthering Heights',
        author: 'Emily Brontë',
        coverUrl: 'https://picsum.photos/300/400?random=23',
        url: 'https://www.gutenberg.org/files/768/768-0.txt',
    },
    {
        id: '36',
        title: 'The War of the Worlds',
        author: 'H.G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=24',
        url: 'https://www.gutenberg.org/files/36/36-0.txt',
    },
    {
        id: '25344',
        title: 'The Scarlet Letter',
        author: 'Nathaniel Hawthorne',
        coverUrl: 'https://picsum.photos/300/400?random=25',
        url: 'https://www.gutenberg.org/files/25344/25344-0.txt',
    },
    {
        id: '1727',
        title: 'The Iliad',
        author: 'Homer',
        coverUrl: 'https://picsum.photos/300/400?random=26',
        url: 'https://www.gutenberg.org/files/1727/1727-0.txt',
    },
     {
        id: '64317',
        title: 'The Great Gatsby',
        author: 'F. Scott Fitzgerald',
        coverUrl: 'https://picsum.photos/300/400?random=9',
        url: 'https://www.gutenberg.org/files/64317/64317-0.txt',
    },
    {
        id: '1952',
        title: 'The Yellow Wallpaper',
        author: 'Charlotte Perkins Gilman',
        coverUrl: 'https://picsum.photos/300/400?random=27',
        url: 'https://www.gutenberg.org/files/1952/1952-0.txt',
    },
    {
        id: '76',
        title: 'Adventures of Huckleberry Finn',
        author: 'Mark Twain',
        coverUrl: 'https://picsum.photos/300/400?random=28',
        url: 'https://www.gutenberg.org/files/76/76-0.txt',
    },
    {
        id: '2542',
        title: 'A Doll\'s House',
        author: 'Henrik Ibsen',
        coverUrl: 'https://picsum.photos/300/400?random=29',
        url: 'https://www.gutenberg.org/files/2542/2542-0.txt',
    },
    {
        id: '16',
        title: 'The Awakening, and Selected Short Stories',
        author: 'Kate Chopin',
        coverUrl: 'https://picsum.photos/300/400?random=30',
        url: 'https://www.gutenberg.org/files/16/16-0.txt',
    },
    {
        id: '219',
        title: 'Heart of Darkness',
        author: 'Joseph Conrad',
        coverUrl: 'https://picsum.photos/300/400?random=31',
        url: 'https://www.gutenberg.org/files/219/219-0.txt',
    },
    {
        id: '43',
        title: 'The Strange Case of Dr. Jekyll and Mr. Hyde',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=32',
        url: 'https://www.gutenberg.org/files/43/43-0.txt',
    },
    {
        id: '1080',
        title: 'The Kama Sutra of Vatsyayana',
        author: 'Vatsyayana',
        coverUrl: 'https://picsum.photos/300/400?random=33',
        url: 'https://www.gutenberg.org/files/1080/1080-0.txt',
    },
    {
        id: '1259',
        title: 'Twenty Thousand Leagues under the Sea',
        author: 'Jules Verne',
        coverUrl: 'https://picsum.photos/300/400?random=34',
        url: 'https://www.gutenberg.org/files/1259/1259-0.txt',
    },
    {
        id: '46',
        title: 'A Christmas Carol',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=35',
        url: 'https://www.gutenberg.org/files/46/46-0.txt',
    },
    {
        id: '1400',
        title: 'Great Expectations',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=36',
        url: 'https://www.gutenberg.org/files/1400/1400-0.txt',
    },
    {
        id: '1232',
        title: 'The Prince',
        author: 'Niccolò Machiavelli',
        coverUrl: 'https://picsum.photos/300/400?random=37',
        url: 'https://www.gutenberg.org/files/1232/1232-0.txt',
    },
    {
        id: '30254',
        title: 'The Romance of Lust',
        author: 'Anonymous',
        coverUrl: 'https://picsum.photos/300/400?random=38',
        url: 'https://www.gutenberg.org/files/30254/30254-0.txt',
    },
    {
        id: '55',
        title: 'The Wonderful Wizard of Oz',
        author: 'L. Frank Baum',
        coverUrl: 'https://picsum.photos/300/400?random=39',
        url: 'https://www.gutenberg.org/files/55/55-0.txt',
    },
    {
        id: '215',
        title: 'The Call of the Wild',
        author: 'Jack London',
        coverUrl: 'https://picsum.photos/300/400?random=40',
        url: 'https://www.gutenberg.org/files/215/215-0.txt',
    },
    {
        id: '1184',
        title: 'The Count of Monte Cristo',
        author: 'Alexandre Dumas',
        coverUrl: 'https://picsum.photos/300/400?random=41',
        url: 'https://www.gutenberg.org/files/1184/1184-0.txt',
    },
    {
        id: '203',
        title: 'The Time Machine',
        author: 'H. G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=42',
        url: 'https://www.gutenberg.org/files/203/203-0.txt',
    },
    {
        id: '28054',
        title: 'The Island of Doctor Moreau',
        author: 'H. G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=43',
        url: 'https://www.gutenberg.org/files/28054/28054-0.txt',
    },
    {
        id: '67979',
        title: 'The Prophet',
        author: 'Kahlil Gibran',
        coverUrl: 'https://picsum.photos/300/400?random=44',
        url: 'https://www.gutenberg.org/files/67979/67979-0.txt',
    },
    {
        id: '135',
        title: 'Les Misérables',
        author: 'Victor Hugo',
        coverUrl: 'https://picsum.photos/300/400?random=45',
        url: 'https://www.gutenberg.org/files/135/135-0.txt',
    },
    {
        id: '1998',
        title: 'The Republic',
        author: 'Plato',
        coverUrl: 'https://picsum.photos/300/400?random=46',
        url: 'https://www.gutenberg.org/files/1998/1998-0.txt',
    },
    {
        id: '3207',
        title: 'Leviathan',
        author: 'Thomas Hobbes',
        coverUrl: 'https://picsum.photos/300/400?random=47',
        url: 'https://www.gutenberg.org/files/3207/3207-0.txt',
    },
    {
        id: '58585',
        title: 'The Communist Manifesto',
        author: 'Karl Marx and Friedrich Engels',
        coverUrl: 'https://picsum.photos/300/400?random=48',
        url: 'https://www.gutenberg.org/files/58585/58585-0.txt',
    },
    {
        id: '2814',
        title: 'Dubliners',
        author: 'James Joyce',
        coverUrl: 'https://picsum.photos/300/400?random=49',
        url: 'https://www.gutenberg.org/files/2814/2814-0.txt',
    },
    {
        id: '4280',
        title: 'A Portrait of the Artist as a Young Man',
        author: 'James Joyce',
        coverUrl: 'https://picsum.photos/300/400?random=50',
        url: 'https://www.gutenberg.org/files/4280/4280-0.txt',
    },
    {
        id: '103',
        title: 'Around the World in Eighty Days',
        author: 'Jules Verne',
        coverUrl: 'https://picsum.photos/300/400?random=51',
        url: 'https://www.gutenberg.org/files/103/103-0.txt',
    },
    {
        id: '829',
        title: 'Gulliver\'s Travels',
        author: 'Jonathan Swift',
        coverUrl: 'https://picsum.photos/300/400?random=52',
        url: 'https://www.gutenberg.org/files/829/829-0.txt',
    },
    {
        id: '209',
        title: 'The Turn of the Screw',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=53',
        url: 'https://www.gutenberg.org/files/209/209-0.txt',
    },
    {
        id: '145',
        title: 'Middlemarch',
        author: 'George Eliot',
        coverUrl: 'https://picsum.photos/300/400?random=54',
        url: 'https://www.gutenberg.org/files/145/145-0.txt',
    },
    {
        id: '1257',
        title: 'The Three Musketeers',
        author: 'Alexandre Dumas',
        coverUrl: 'https://picsum.photos/300/400?random=55',
        url: 'https://www.gutenberg.org/files/1257/1257-0.txt',
    },
    {
        id: '27827',
        title: 'The Brothers Karamazov',
        author: 'Fyodor Dostoevsky',
        coverUrl: 'https://picsum.photos/300/400?random=56',
        url: 'https://www.gutenberg.org/files/27827/27827-0.txt',
    },
    {
        id: '6130',
        title: 'The Iliad of Homer',
        author: 'Homer, translated by Alexander Pope',
        coverUrl: 'https://picsum.photos/300/400?random=57',
        url: 'https://www.gutenberg.org/files/6130/6130-0.txt'
    },
    {
        id: '1728',
        title: 'The Odyssey',
        author: 'Homer',
        coverUrl: 'https://picsum.photos/300/400?random=58',
        url: 'https://www.gutenberg.org/files/1728/1728-0.txt'
    },
    {
        id: '2852',
        title: 'The Hound of the Baskervilles',
        author: 'Arthur Conan Doyle',
        coverUrl: 'https://picsum.photos/300/400?random=59',
        url: 'https://www.gutenberg.org/files/2852/2852-0.txt'
    },
    {
        id: '205',
        title: 'Walden, and On The Duty Of Civil Disobedience',
        author: 'Henry David Thoreau',
        coverUrl: 'https://picsum.photos/300/400?random=60',
        url: 'https://www.gutenberg.org/files/205/205-0.txt'
    },
    {
        id: '16328',
        title: 'Beowulf',
        author: 'Anonymous',
        coverUrl: 'https://picsum.photos/300/400?random=61',
        url: 'https://www.gutenberg.org/files/16328/16328-0.txt'
    },
    {
        id: '1064',
        title: 'The Canterbury Tales, and Other Poems',
        author: 'Geoffrey Chaucer',
        coverUrl: 'https://picsum.photos/300/400?random=62',
        url: 'https://www.gutenberg.org/files/1064/1064-0.txt'
    },
    {
        id: '158',
        title: 'Emma',
        author: 'Jane Austen',
        coverUrl: 'https://picsum.photos/300/400?random=63',
        url: 'https://www.gutenberg.org/files/158/158-0.txt'
    },
    {
        id: '946',
        title: 'David Copperfield',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=64',
        url: 'https://www.gutenberg.org/files/946/946-0.txt'
    },
    {
        id: '14264',
        title: 'The Jungle Book',
        author: 'Rudyard Kipling',
        coverUrl: 'https://picsum.photos/300/400?random=65',
        url: 'https://www.gutenberg.org/files/14264/14264-0.txt'
    },
    {
        id: '244',
        title: 'A Study in Scarlet',
        author: 'Arthur Conan Doyle',
        coverUrl: 'https://picsum.photos/300/400?random=66',
        url: 'https://www.gutenberg.org/files/244/244-0.txt'
    },
    {
        id: '16389',
        title: 'The Memoirs of Sherlock Holmes',
        author: 'Arthur Conan Doyle',
        coverUrl: 'https://picsum.photos/300/400?random=67',
        url: 'https://www.gutenberg.org/files/16389/16389-0.txt'
    },
    {
        id: '8800',
        title: 'The Return of Sherlock Holmes',
        author: 'Arthur Conan Doyle',
        coverUrl: 'https://picsum.photos/300/400?random=68',
        url: 'https://www.gutenberg.org/files/8800/8800-0.txt'
    },
    {
        id: '108',
        title: 'The Sign of the Four',
        author: 'Arthur Conan Doyle',
        coverUrl: 'https://picsum.photos/300/400?random=69',
        url: 'https://www.gutenberg.org/files/108/108-0.txt'
    },
    {
        id: '23',
        title: 'The Narrative of the Life of Frederick Douglass',
        author: 'Frederick Douglass',
        coverUrl: 'https://picsum.photos/300/400?random=70',
        url: 'https://www.gutenberg.org/files/23/23-0.txt'
    },
    {
        id: '514',
        title: 'Little Women',
        author: 'Louisa May Alcott',
        coverUrl: 'https://picsum.photos/300/400?random=71',
        url: 'https://www.gutenberg.org/files/514/514-0.txt'
    },
    {
        id: '2641',
        title: 'A Room with a View',
        author: 'E. M. Forster',
        coverUrl: 'https://picsum.photos/300/400?random=72',
        url: 'https://www.gutenberg.org/files/2641/2641-0.txt'
    },
    {
        id: '394',
        title: 'Cranford',
        author: 'Elizabeth Gaskell',
        coverUrl: 'https://picsum.photos/300/400?random=73',
        url: 'https://www.gutenberg.org/files/394/394-0.txt'
    },
    {
        id: '4085',
        title: 'The Age of Innocence',
        author: 'Edith Wharton',
        coverUrl: 'https://picsum.photos/300/400?random=74',
        url: 'https://www.gutenberg.org/files/4085/4085-0.txt'
    },
    {
        id: '37106',
        title: 'The Secret Garden',
        author: 'Frances Hodgson Burnett',
        coverUrl: 'https://picsum.photos/300/400?random=75',
        url: 'https://www.gutenberg.org/files/37106/37106-0.txt'
    },
    {
        id: '2591',
        title: 'The House of Mirth',
        author: 'Edith Wharton',
        coverUrl: 'https://picsum.photos/300/400?random=76',
        url: 'https://www.gutenberg.org/files/2591/2591-0.txt'
    },
    {
        id: '19337',
        title: 'The Wind in the Willows',
        author: 'Kenneth Grahame',
        coverUrl: 'https://picsum.photos/300/400?random=77',
        url: 'https://www.gutenberg.org/files/19337/19337-0.txt'
    },
    {
        id: '2554',
        title: 'Crime and Punishment',
        author: 'Fyodor Dostoevsky',
        coverUrl: 'https://picsum.photos/300/400?random=78',
        url: 'https://www.gutenberg.org/files/2554/2554-0.txt'
    },
    {
        id: '61533',
        title: 'The Idiot',
        author: 'Fyodor Dostoevsky',
        coverUrl: 'https://picsum.photos/300/400?random=79',
        url: 'https://www.gutenberg.org/files/61533/61533-0.txt'
    },
    {
        id: '600',
        title: 'Notes from the Underground',
        author: 'Fyodor Dostoevsky',
        coverUrl: 'https://picsum.photos/300/400?random=80',
        url: 'https://www.gutenberg.org/files/600/600-0.txt'
    },
    {
        id: '1250',
        title: 'Madame Bovary',
        author: 'Gustave Flaubert',
        coverUrl: 'https://picsum.photos/300/400?random=81',
        url: 'https://www.gutenberg.org/files/1250/1250-0.txt'
    },
    {
        id: '161',
        title: 'Sense and Sensibility',
        author: 'Jane Austen',
        coverUrl: 'https://picsum.photos/300/400?random=82',
        url: 'https://www.gutenberg.org/files/161/161-0.txt'
    },
    {
        id: '105',
        title: 'Persuasion',
        author: 'Jane Austen',
        coverUrl: 'https://picsum.photos/300/400?random=83',
        url: 'https://www.gutenberg.org/files/105/105-0.txt',
    },
    {
        id: '141',
        title: 'Mansfield Park',
        author: 'Jane Austen',
        coverUrl: 'https://picsum.photos/300/400?random=84',
        url: 'https://www.gutenberg.org/files/141/141-0.txt'
    },
    {
        id: '1212',
        title: 'Northanger Abbey',
        author: 'Jane Austen',
        coverUrl: 'https://picsum.photos/300/400?random=85',
        url: 'https://www.gutenberg.org/files/1212/1212-0.txt'
    },
    {
        id: '20228',
        title: 'The Red Badge of Courage',
        author: 'Stephen Crane',
        coverUrl: 'https://picsum.photos/300/400?random=86',
        url: 'https://www.gutenberg.org/files/20228/20228-0.txt'
    },
    {
        id: '42',
        title: 'The Merry Adventures of Robin Hood',
        author: 'Howard Pyle',
        coverUrl: 'https://picsum.photos/300/400?random=87',
        url: 'https://www.gutenberg.org/files/42/42-0.txt'
    },
    {
        id: '41',
        title: 'The Legend of Sleepy Hollow',
        author: 'Washington Irving',
        coverUrl: 'https://picsum.photos/300/400?random=88',
        url: 'https://www.gutenberg.org/files/41/41-0.txt'
    },
    {
        id: '20',
        title: 'Paradise Lost',
        author: 'John Milton',
        coverUrl: 'https://picsum.photos/300/400?random=89',
        url: 'https://www.gutenberg.org/files/20/20-0.txt'
    },
    {
        id: '33',
        title: 'The Scarlet Pimpernel',
        author: 'Baroness Orczy',
        coverUrl: 'https://picsum.photos/300/400?random=90',
        url: 'https://www.gutenberg.org/files/33/33-0.txt'
    },
    {
        id: '82',
        title: 'Ivanhoe',
        author: 'Walter Scott',
        coverUrl: 'https://picsum.photos/300/400?random=91',
        url: 'https://www.gutenberg.org/files/82/82-0.txt'
    },
    {
        id: '2705',
        title: 'The Last of the Mohicans',
        author: 'James Fenimore Cooper',
        coverUrl: 'https://picsum.photos/300/400?random=92',
        url: 'https://www.gutenberg.org/files/2705/2705-0.txt'
    },
    {
        id: '1837',
        title: 'The Last Man',
        author: 'Mary Shelley',
        coverUrl: 'https://picsum.photos/300/400?random=93',
        url: 'https://www.gutenberg.org/files/1837/1837-0.txt'
    },
    {
        id: '521',
        title: 'The Life and Adventures of Robinson Crusoe',
        author: 'Daniel Defoe',
        coverUrl: 'https://picsum.photos/300/400?random=94',
        url: 'https://www.gutenberg.org/files/521/521-0.txt'
    },
    {
        id: '3825',
        title: 'Pygmalion',
        author: 'George Bernard Shaw',
        coverUrl: 'https://picsum.photos/300/400?random=95',
        url: 'https://www.gutenberg.org/files/3825/3825-0.txt'
    },
    {
        id: '1155',
        title: 'The Importance of Being Earnest',
        author: 'Oscar Wilde',
        coverUrl: 'https://picsum.photos/300/400?random=96',
        url: 'https://www.gutenberg.org/files/1155/1155-0.txt'
    },
    {
        id: '245',
        title: 'The Man Who Was Thursday',
        author: 'G.K. Chesterton',
        coverUrl: 'https://picsum.photos/300/400?random=97',
        url: 'https://www.gutenberg.org/files/245/245-0.txt'
    },
    {
        id: '1322',
        title: 'Leaves of Grass',
        author: 'Walt Whitman',
        coverUrl: 'https://picsum.photos/300/400?random=98',
        url: 'https://www.gutenberg.org/files/1322/1322-0.txt'
    },
    {
        id: '19942',
        title: 'The Divine Comedy',
        author: 'Dante Alighieri',
        coverUrl: 'https://picsum.photos/300/400?random=99',
        url: 'https://www.gutenberg.org/files/19942/19942-0.txt'
    },
    {
        id: '1513',
        title: 'Romeo and Juliet',
        author: 'William Shakespeare',
        coverUrl: 'https://picsum.photos/300/400?random=100',
        url: 'https://www.gutenberg.org/files/1513/1513-0.txt'
    },
    {
        id: '1533',
        title: 'Hamlet',
        author: 'William Shakespeare',
        coverUrl: 'https://picsum.photos/300/400?random=101',
        url: 'https://www.gutenberg.org/files/1533/1533-0.txt'
    },
    {
        id: '1524',
        title: 'Macbeth',
        author: 'William Shakespeare',
        coverUrl: 'https://picsum.photos/300/400?random=102',
        url: 'https://www.gutenberg.org/files/1524/1524-0.txt'
    },
    {
        id: '2265',
        title: 'Othello',
        author: 'William Shakespeare',
        coverUrl: 'https://picsum.photos/300/400?random=103',
        url: 'https://www.gutenberg.org/files/2265/2265-0.txt'
    },
    {
        id: '2267',
        title: 'The Tempest',
        author: 'William Shakespeare',
        coverUrl: 'https://picsum.photos/300/400?random=104',
        url: 'https://www.gutenberg.org/files/2267/2267-0.txt'
    },
    {
        id: '1795',
        title: 'A Midsummer Night\'s Dream',
        author: 'William Shakespeare',
        coverUrl: 'https://picsum.photos/300/400?random=105',
        url: 'https://www.gutenberg.org/files/1795/1795-0.txt'
    },
    {
        id: '2264',
        title: 'The Taming of the Shrew',
        author: 'William Shakespeare',
        coverUrl: 'https://picsum.photos/300/400?random=106',
        url: 'https://www.gutenberg.org/files/2264/2264-0.txt'
    },
    {
        id: '2266',
        title: 'The Merchant of Venice',
        author: 'William Shakespeare',
        coverUrl: 'https://picsum.photos/300/400?random=107',
        url: 'https://www.gutenberg.org/files/2266/2266-0.txt',
    },
    {
        id: '1787',
        title: 'King Lear',
        author: 'William Shakespeare',
        coverUrl: 'https://picsum.photos/300/400?random=108',
        url: 'https://www.gutenberg.org/files/1787/1787-0.txt',
    },
    {
        id: '23042',
        title: 'The Complete Works of William Shakespeare',
        author: 'William Shakespeare',
        coverUrl: 'https://picsum.photos/300/400?random=109',
        url: 'https://www.gutenberg.org/files/23042/23042-0.txt',
    },
    {
        id: '132',
        title: 'The Art of War',
        author: 'Sun Tzu',
        coverUrl: 'https://picsum.photos/300/400?random=110',
        url: 'https://www.gutenberg.org/files/132/132-0.txt',
    },
    {
        id: '5000',
        title: 'Thus Spake Zarathustra',
        author: 'Friedrich Nietzsche',
        coverUrl: 'https://picsum.photos/300/400?random=111',
        url: 'https://www.gutenberg.org/files/5000/5000-0.txt',
    },
    {
        id: '4363',
        title: 'Beyond Good and Evil',
        author: 'Friedrich Nietzsche',
        coverUrl: 'https://picsum.photos/300/400?random=112',
        url: 'https://www.gutenberg.org/files/4363/4363-0.txt',
    },
    {
        id: '2848',
        title: 'The Antichrist',
        author: 'Friedrich Nietzsche',
        coverUrl: 'https://picsum.photos/300/400?random=113',
        url: 'https://www.gutenberg.org/files/2848/2848-0.txt',
    },
    {
        id: '3800',
        title: 'The Critique of Pure Reason',
        author: 'Immanuel Kant',
        coverUrl: 'https://picsum.photos/300/400?random=114',
        url: 'https://www.gutenberg.org/files/3800/3800-0.txt',
    },
    {
        id: '574',
        title: 'The Souls of Black Folk',
        author: 'W. E. B. Du Bois',
        coverUrl: 'https://picsum.photos/300/400?random=115',
        url: 'https://www.gutenberg.org/files/574/574-0.txt',
    },
    {
        id: '32',
        title: 'Herland',
        author: 'Charlotte Perkins Gilman',
        coverUrl: 'https://picsum.photos/300/400?random=116',
        url: 'https://www.gutenberg.org/files/32/32-0.txt',
    },
    {
        id: '30',
        title: 'Little Women',
        author: 'Louisa May Alcott',
        coverUrl: 'https://picsum.photos/300/400?random=117',
        url: 'https://www.gutenberg.org/files/30/30-0.txt',
    },
    {
        id: '2708',
        title: 'The Pathfinder',
        author: 'James Fenimore Cooper',
        coverUrl: 'https://picsum.photos/300/400?random=118',
        url: 'https://www.gutenberg.org/files/2708/2708-0.txt',
    },
    {
        id: '940',
        title: 'The Deerslayer',
        author: 'James Fenimore Cooper',
        coverUrl: 'https://picsum.photos/300/400?random=119',
        url: 'https://www.gutenberg.org/files/940/940-0.txt',
    },
    {
        id: '18657',
        title: 'The Prairie',
        author: 'James Fenimore Cooper',
        coverUrl: 'https://picsum.photos/300/400?random=120',
        url: 'https://www.gutenberg.org/files/18657/18657-0.txt',
    },
    {
        id: '24022',
        title: 'The Pioneers',
        author: 'James Fenimore Cooper',
        coverUrl: 'https://picsum.photos/300/400?random=121',
        url: 'https://www.gutenberg.org/files/24022/24022-0.txt',
    },
    {
        id: '100',
        title: 'The Complete Works of William Shakespeare',
        author: 'William Shakespeare',
        coverUrl: 'https://picsum.photos/300/400?random=122',
        url: 'https://www.gutenberg.org/files/100/100-0.txt',
    },
    {
        id: '2595',
        title: 'The Innocents Abroad',
        author: 'Mark Twain',
        coverUrl: 'https://picsum.photos/300/400?random=123',
        url: 'https://www.gutenberg.org/files/2595/2595-0.txt',
    },
    {
        id: '18372',
        title: 'Roughing It',
        author: 'Mark Twain',
        coverUrl: 'https://picsum.photos/300/400?random=124',
        url: 'https://www.gutenberg.org/files/18372/18372-0.txt',
    },
    {
        id: '86',
        title: 'A Connecticut Yankee in King Arthur\'s Court',
        author: 'Mark Twain',
        coverUrl: 'https://picsum.photos/300/400?random=125',
        url: 'https://www.gutenberg.org/files/86/86-0.txt',
    },
    {
        id: '102',
        title: 'The Prince and the Pauper',
        author: 'Mark Twain',
        coverUrl: 'https://picsum.photos/300/400?random=126',
        url: 'https://www.gutenberg.org/files/102/102-0.txt',
    },
    {
        id: '2450',
        title: 'The Mysterious Stranger',
        author: 'Mark Twain',
        coverUrl: 'https://picsum.photos/300/400?random=127',
        url: 'https://www.gutenberg.org/files/2450/2450-0.txt',
    },
    {
        id: '3176',
        title: 'The American Claimant',
        author: 'Mark Twain',
        coverUrl: 'https://picsum.photos/300/400?random=128',
        url: 'https://www.gutenberg.org/files/3176/3176-0.txt',
    },
    {
        id: '3177',
        title: 'The £1,000,000 Bank-Note',
        author: 'Mark Twain',
        coverUrl: 'https://picsum.photos/300/400?random=129',
        url: 'https://www.gutenberg.org/files/3177/3177-0.txt',
    },
    {
        id: '3190',
        title: 'The Tragedy of Pudd\'nhead Wilson',
        author: 'Mark Twain',
        coverUrl: 'https://picsum.photos/300/400?random=130',
        url: 'https://www.gutenberg.org/files/3190/3190-0.txt',
    },
    {
        id: '2890',
        title: 'Following the Equator',
        author: 'Mark Twain',
        coverUrl: 'https://picsum.photos/300/400?random=131',
        url: 'https://www.gutenberg.org/files/2890/2890-0.txt',
    },
    {
        id: '142',
        title: 'Hard Times',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=132',
        url: 'https://www.gutenberg.org/files/142/142-0.txt',
    },
    {
        id: '580',
        title: 'The Pickwick Papers',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=133',
        url: 'https://www.gutenberg.org/files/580/580-0.txt',
    },
    {
        id: '730',
        title: 'Oliver Twist',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=134',
        url: 'https://www.gutenberg.org/files/730/730-0.txt',
    },
    {
        id: '882',
        title: 'Nicholas Nickleby',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=135',
        url: 'https://www.gutenberg.org/files/882/882-0.txt',
    },
    {
        id: '675',
        title: 'The Old Curiosity Shop',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=136',
        url: 'https://www.gutenberg.org/files/675/675-0.txt',
    },
    {
        id: '700',
        title: 'Barnaby Rudge',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=137',
        url: 'https://www.gutenberg.org/files/700/700-0.txt',
    },
    {
        id: '821',
        title: 'Martin Chuzzlewit',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=138',
        url: 'https://www.gutenberg.org/files/821/821-0.txt',
    },
    {
        id: '967',
        title: 'Dombey and Son',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=139',
        url: 'https://www.gutenberg.org/files/967/967-0.txt',
    },
    {
        id: '564',
        title: 'Bleak House',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=140',
        url: 'https://www.gutenberg.org/files/564/564-0.txt',
    },
    {
        id: '968',
        title: 'Little Dorrit',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=141',
        url: 'https://www.gutenberg.org/files/968/968-0.txt',
    },
    {
        id: '786',
        title: 'Our Mutual Friend',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=142',
        url: 'https://www.gutenberg.org/files/786/786-0.txt',
    },
    {
        id: '963',
        title: 'The Mystery of Edwin Drood',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=143',
        url: 'https://www.gutenberg.org/files/963/963-0.txt',
    },
    {
        id: '204',
        title: 'The Invisible Man',
        author: 'H. G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=144',
        url: 'https://www.gutenberg.org/files/204/204-0.txt',
    },
    {
        id: '35',
        title: 'The Time Machine',
        author: 'H. G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=145',
        url: 'https://www.gutenberg.org/files/35/35-0.txt',
    },
    {
        id: '159',
        title: 'The War of the Worlds',
        author: 'H. G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=146',
        url: 'https://www.gutenberg.org/files/159/159-0.txt',
    },
    {
        id: '5230',
        title: 'The First Men in the Moon',
        author: 'H. G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=147',
        url: 'https://www.gutenberg.org/files/5230/5230-0.txt',
    },
    {
        id: '1187',
        title: 'The Food of the Gods and How It Came to Earth',
        author: 'H. G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=148',
        url: 'https://www.gutenberg.org/files/1187/1187-0.txt',
    },
    {
        id: '59774',
        title: 'The Shape of Things to Come',
        author: 'H. G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=149',
        url: 'https://www.gutenberg.org/files/59774/59774-0.txt',
    },
    {
        id: '2236',
        title: 'The History of Mr. Polly',
        author: 'H. G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=150',
        url: 'https://www.gutenberg.org/files/2236/2236-0.txt',
    },
    {
        id: '1169',
        title: 'Kipps: The Story of a Simple Soul',
        author: 'H. G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=151',
        url: 'https://www.gutenberg.org/files/1169/1169-0.txt',
    },
    {
        id: '59775',
        title: 'The World Set Free',
        author: 'H. G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=152',
        url: 'https://www.gutenberg.org/files/59775/59775-0.txt',
    },
    {
        id: '644',
        title: 'The Sleeper Awakes',
        author: 'H. G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=153',
        url: 'https://www.gutenberg.org/files/644/644-0.txt',
    },
    {
        id: '2247',
        title: 'The New Machiavelli',
        author: 'H. G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=154',
        url: 'https://www.gutenberg.org/files/2247/2247-0.txt',
    },
    {
        id: '155',
        title: 'The Secret Agent: A Simple Tale',
        author: 'Joseph Conrad',
        coverUrl: 'https://picsum.photos/300/400?random=155',
        url: 'https://www.gutenberg.org/files/155/155-0.txt',
    },
    {
        id: '220',
        title: 'Lord Jim',
        author: 'Joseph Conrad',
        coverUrl: 'https://picsum.photos/300/400?random=156',
        url: 'https://www.gutenberg.org/files/220/220-0.txt',
    },
    {
        id: '95',
        title: 'Nostromo: A Tale of the Seaboard',
        author: 'Joseph Conrad',
        coverUrl: 'https://picsum.photos/300/400?random=157',
        url: 'https://www.gutenberg.org/files/95/95-0.txt',
    },
    {
        id: '2025',
        title: 'Under Western Eyes',
        author: 'Joseph Conrad',
        coverUrl: 'https://picsum.photos/300/400?random=158',
        url: 'https://www.gutenberg.org/files/2025/2025-0.txt',
    },
    {
        id: '499',
        title: 'The Rover',
        author: 'Joseph Conrad',
        coverUrl: 'https://picsum.photos/300/400?random=159',
        url: 'https://www.gutenberg.org/files/499/499-0.txt',
    },
    {
        id: '525',
        title: 'The Arrow of Gold',
        author: 'Joseph Conrad',
        coverUrl: 'https://picsum.photos/300/400?random=160',
        url: 'https://www.gutenberg.org/files/525/525-0.txt',
    },
    {
        id: '526',
        title: 'Victory: An Island Tale',
        author: 'Joseph Conrad',
        coverUrl: 'https://picsum.photos/300/400?random=161',
        url: 'https://www.gutenberg.org/files/526/526-0.txt',
    },
    {
        id: '524',
        title: 'Chance',
        author: 'Joseph Conrad',
        coverUrl: 'https://picsum.photos/300/400?random=162',
        url: 'https://www.gutenberg.org/files/524/524-0.txt',
    },
    {
        id: '475',
        title: 'The Shadow Line',
        author: 'Joseph Conrad',
        coverUrl: 'https://picsum.photos/300/400?random=163',
        url: 'https://www.gutenberg.org/files/475/475-0.txt',
    },
    {
        id: '2014',
        title: 'A Personal Record',
        author: 'Joseph Conrad',
        coverUrl: 'https://picsum.photos/300/400?random=164',
        url: 'https://www.gutenberg.org/files/2014/2014-0.txt',
    },
    {
        id: '185',
        title: 'The Voyage Out',
        author: 'Virginia Woolf',
        coverUrl: 'https://picsum.photos/300/400?random=165',
        url: 'https://www.gutenberg.org/files/185/185-0.txt',
    },
    {
        id: '67702',
        title: 'Mrs Dalloway',
        author: 'Virginia Woolf',
        coverUrl: 'https://picsum.photos/300/400?random=166',
        url: 'https://www.gutenberg.org/files/67702/67702-0.txt',
    },
    {
        id: '67918',
        title: 'To the Lighthouse',
        author: 'Virginia Woolf',
        coverUrl: 'https://picsum.photos/300/400?random=167',
        url: 'https://www.gutenberg.org/files/67918/67918-0.txt',
    },
    {
        id: '67926',
        title: 'Orlando: A Biography',
        author: 'Virginia Woolf',
        coverUrl: 'https://picsum.photos/300/400?random=168',
        url: 'https://www.gutenberg.org/files/67926/67926-0.txt',
    },
    {
        id: '67980',
        title: 'A Room of One\'s Own',
        author: 'Virginia Woolf',
        coverUrl: 'https://picsum.photos/300/400?random=169',
        url: 'https://www.gutenberg.org/files/67980/67980-0.txt',
    },
    {
        id: '67927',
        title: 'The Waves',
        author: 'Virginia Woolf',
        coverUrl: 'https://picsum.photos/300/400?random=170',
        url: 'https://www.gutenberg.org/files/67927/67927-0.txt',
    },
    {
        id: '1589',
        title: 'Night and Day',
        author: 'Virginia Woolf',
        coverUrl: 'https://picsum.photos/300/400?random=171',
        url: 'https://www.gutenberg.org/files/1589/1589-0.txt',
    },
    {
        id: '2863',
        title: 'Jacob\'s Room',
        author: 'Virginia Woolf',
        coverUrl: 'https://picsum.photos/300/400?random=172',
        url: 'https://www.gutenberg.org/files/2863/2863-0.txt',
    },
    {
        id: '4079',
        title: 'The Common Reader',
        author: 'Virginia Woolf',
        coverUrl: 'https://picsum.photos/300/400?random=173',
        url: 'https://www.gutenberg.org/files/4079/4079-0.txt',
    },
    {
        id: '3335',
        title: 'The Second Common Reader',
        author: 'Virginia Woolf',
        coverUrl: 'https://picsum.photos/300/400?random=174',
        url: 'https://www.gutenberg.org/files/3335/3335-0.txt',
    },
    {
        id: '2875',
        title: 'Monday or Tuesday',
        author: 'Virginia Woolf',
        coverUrl: 'https://picsum.photos/300/400?random=175',
        url: 'https://www.gutenberg.org/files/2875/2875-0.txt',
    },
    {
        id: '121',
        title: 'Kidnapped',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=176',
        url: 'https://www.gutenberg.org/files/121/121-0.txt',
    },
    {
        id: '421',
        title: 'The Black Arrow',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=177',
        url: 'https://www.gutenberg.org/files/421/421-0.txt',
    },
    {
        id: '75',
        title: 'The Master of Ballantrae',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=178',
        url: 'https://www.gutenberg.org/files/75/75-0.txt',
    },
    {
        id: '3093',
        title: 'Catriona',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=179',
        url: 'https://www.gutenberg.org/files/3093/3093-0.txt',
    },
    {
        id: '417',
        title: 'The Wrecker',
        author: 'Robert Louis Stevenson and Lloyd Osbourne',
        coverUrl: 'https://picsum.photos/300/400?random=180',
        url: 'https://www.gutenberg.org/files/417/417-0.txt',
    },
    {
        id: '535',
        title: 'The Ebb-Tide',
        author: 'Robert Louis Stevenson and Lloyd Osbourne',
        coverUrl: 'https://picsum.photos/300/400?random=181',
        url: 'https://www.gutenberg.org/files/535/535-0.txt',
    },
    {
        id: '536',
        title: 'Island Nights\' Entertainments',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=182',
        url: 'https://www.gutenberg.org/files/536/536-0.txt',
    },
    {
        id: '1249',
        title: 'An Inland Voyage',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=183',
        url: 'https://www.gutenberg.org/files/1249/1249-0.txt',
    },
    {
        id: '505',
        title: 'Travels with a Donkey in the Cévennes',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=184',
        url: 'https://www.gutenberg.org/files/505/505-0.txt',
    },
    {
        id: '416',
        title: 'Virginibus Puerisque, and Other Papers',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=185',
        url: 'https://www.gutenberg.org/files/416/416-0.txt',
    },
    {
        id: '447',
        title: 'The New Arabian Nights',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=186',
        url: 'https://www.gutenberg.org/files/447/447-0.txt',
    },
    {
        id: '415',
        title: 'The Merry Men, and Other Tales and Fables',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=187',
        url: 'https://www.gutenberg.org/files/415/415-0.txt',
    },
    {
        id: '307',
        title: 'The Dynamiter',
        author: 'Robert Louis Stevenson and Fanny Van de Grift Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=188',
        url: 'https://www.gutenberg.org/files/307/307-0.txt',
    },
    {
        id: '298',
        title: 'The Wrong Box',
        author: 'Robert Louis Stevenson and Lloyd Osbourne',
        coverUrl: 'https://picsum.photos/300/400?random=189',
        url: 'https://www.gutenberg.org/files/298/298-0.txt',
    },
    {
        id: '299',
        title: 'A Footnote to History: Eight Years of Trouble in Samoa',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=190',
        url: 'https://www.gutenberg.org/files/299/299-0.txt',
    },
    {
        id: '348',
        title: 'The Silverado Squatters',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=191',
        url: 'https://www.gutenberg.org/files/348/348-0.txt',
    },
    {
        id: '297',
        title: 'Across the Plains, with Other Memories and Essays',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=192',
        url: 'https://www.gutenberg.org/files/297/297-0.txt',
    },
    {
        id: '208',
        title: 'Familiar Studies of Men and Books',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=193',
        url: 'https://www.gutenberg.org/files/208/208-0.txt',
    },
    {
        id: '296',
        title: 'Memories and Portraits',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=194',
        url: 'https://www.gutenberg.org/files/296/296-0.txt',
    },
    {
        id: '295',
        title: 'A Child\'s Garden of Verses',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=195',
        url: 'https://www.gutenberg.org/files/295/295-0.txt',
    },
    {
        id: '382',
        title: 'Underwoods',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=196',
        url: 'https://www.gutenberg.org/files/382/382-0.txt',
    },
    {
        id: '503',
        title: 'Ballads',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=197',
        url: 'https://www.gutenberg.org/files/503/503-0.txt',
    },
    {
        id: '30990',
        title: 'Songs of Travel, and Other Verses',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=198',
        url: 'https://www.gutenberg.org/files/30990/30990-0.txt',
    },
    {
        id: '228',
        title: 'The Man in the Iron Mask',
        author: 'Alexandre Dumas',
        coverUrl: 'https://picsum.photos/300/400?random=199',
        url: 'https://www.gutenberg.org/files/228/228-0.txt',
    },
    {
        id: '1258',
        title: 'Twenty Years After',
        author: 'Alexandre Dumas',
        coverUrl: 'https://picsum.photos/300/400?random=200',
        url: 'https://www.gutenberg.org/files/1258/1258-0.txt',
    },
    {
        id: '2680',
        title: 'The Vicomte de Bragelonne',
        author: 'Alexandre Dumas',
        coverUrl: 'https://picsum.photos/300/400?random=201',
        url: 'https://www.gutenberg.org/files/2680/2680-0.txt',
    },
    {
        id: '1013',
        title: 'The Black Tulip',
        author: 'Alexandre Dumas',
        coverUrl: 'https://picsum.photos/300/400?random=202',
        url: 'https://www.gutenberg.org/files/1013/1013-0.txt',
    },
    {
        id: '965',
        title: 'The Queen\'s Necklace',
        author: 'Alexandre Dumas',
        coverUrl: 'https://picsum.photos/300/400?random=203',
        url: 'https://www.gutenberg.org/files/965/965-0.txt',
    },
    {
        id: '1769',
        title: 'The Man Who Laughs',
        author: 'Victor Hugo',
        coverUrl: 'https://picsum.photos/300/400?random=204',
        url: 'https://www.gutenberg.org/files/1769/1769-0.txt',
    },
    {
        id: '2527',
        title: 'The Toilers of the Sea',
        author: 'Victor Hugo',
        coverUrl: 'https://picsum.photos/300/400?random=205',
        url: 'https://www.gutenberg.org/files/2527/2527-0.txt',
    },
    {
        id: '125',
        title: 'The Hunchback of Notre Dame',
        author: 'Victor Hugo',
        coverUrl: 'https://picsum.photos/300/400?random=206',
        url: 'https://www.gutenberg.org/files/125/125-0.txt',
    }
];
