
export type LibraryBook = {
    id: string;
    title: string;
    author: string;
    coverUrl: string;
    url: string;
};

// All books are from Project Gutenberg (public domain)
// URLs point to the plain text files for in-app reading.
export const LIBRARY_BOOKS: LibraryBook[] = [
    {
        id: '84',
        title: 'Frankenstein',
        author: 'Mary Shelley',
        coverUrl: 'https://picsum.photos/300/400?random=11',
        url: 'https://www.gutenberg.org/files/84/84-0.txt',
    },
    {
        id: '2701',
        title: 'Moby Dick; or, The Whale',
        author: 'Herman Melville',
        coverUrl: 'https://picsum.photos/300/400?random=4',
        url: 'https://www.gutenberg.org/files/2701/2701-0.txt',
    },
    {
        id: '1661',
        title: 'The Adventures of Sherlock Holmes',
        author: 'Arthur Conan Doyle',
        coverUrl: 'https://picsum.photos/300/400?random=1',
        url: 'https://www.gutenberg.org/files/1661/1661-0.txt'
    },
    {
        id: '1342',
        title: 'Pride and Prejudice',
        author: 'Jane Austen',
        coverUrl: 'https://picsum.photos/300/400?random=10',
        url: 'https://www.gutenberg.org/files/1342/1342-0.txt',
    },
    {
        id: '345',
        title: 'Dracula',
        author: 'Bram Stoker',
        coverUrl: 'https://picsum.photos/300/400?random=12',
        url: 'https://www.gutenberg.org/files/345/345-0.txt',
    },
    {
        id: '98',
        title: 'A Tale of Two Cities',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=13',
        url: 'https://www.gutenberg.org/files/98/98-0.txt',
    },
    {
        id: '74',
        title: 'The Adventures of Tom Sawyer',
        author: 'Mark Twain',
        coverUrl: 'https://picsum.photos/300/400?random=14',
        url: 'https://www.gutenberg.org/files/74/74-0.txt',
    },
    {
        id: '174',
        title: 'The Picture of Dorian Gray',
        author: 'Oscar Wilde',
        coverUrl: 'https://picsum.photos/300/400?random=15',
        url: 'https://www.gutenberg.org/files/174/174-0.txt',
    },
    {
        id: '11',
        title: 'Alice\'s Adventures in Wonderland',
        author: 'Lewis Carroll',
        coverUrl: 'https://picsum.photos/300/400?random=6',
        url: 'https://www.gutenberg.org/files/11/11-0.txt'
    },
    {
        id: '5200',
        title: 'Metamorphosis',
        author: 'Franz Kafka',
        coverUrl: 'https://picsum.photos/300/400?random=17',
        url: 'https://www.gutenberg.org/files/5200/5200-0.txt',
    },
    {
        id: '4300',
        title: 'Ulysses',
        author: 'James Joyce',
        coverUrl: 'https://picsum.photos/300/400?random=18',
        url: 'https://www.gutenberg.org/files/4300/4300-0.txt',
    },
    {
        id: '2600',
        title: 'War and Peace',
        author: 'Leo Tolstoy',
        coverUrl: 'https://picsum.photos/300/400?random=19',
        url: 'https://www.gutenberg.org/files/2600/2600-0.txt',
    },
    {
        id: '996',
        title: 'Don Quixote',
        author: 'Miguel de Cervantes',
        coverUrl: 'https://picsum.photos/300/400?random=20',
        url: 'https://www.gutenberg.org/files/996/996-0.txt',
    },
    {
        id: '120',
        title: 'Treasure Island',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=21',
        url: 'https://www.gutenberg.org/files/120/120-0.txt',
    },
    {
        id: '1260',
        title: 'Jane Eyre',
        author: 'Charlotte Brontë',
        coverUrl: 'https://picsum.photos/300/400?random=22',
        url: 'https://www.gutenberg.org/files/1260/1260-0.txt',
    },
    {
        id: '768',
        title: 'Wuthering Heights',
        author: 'Emily Brontë',
        coverUrl: 'https://picsum.photos/300/400?random=23',
        url: 'https://www.gutenberg.org/files/768/768-0.txt',
    },
    {
        id: '36',
        title: 'The War of the Worlds',
        author: 'H.G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=24',
        url: 'https://www.gutenberg.org/files/36/36-0.txt',
    },
    {
        id: '25344',
        title: 'The Scarlet Letter',
        author: 'Nathaniel Hawthorne',
        coverUrl: 'https://picsum.photos/300/400?random=25',
        url: 'https://www.gutenberg.org/files/25344/25344-0.txt',
    },
    {
        id: '1727',
        title: 'The Iliad',
        author: 'Homer',
        coverUrl: 'https://picsum.photos/300/400?random=26',
        url: 'https://www.gutenberg.org/files/1727/1727-0.txt',
    },
     {
        id: '64317',
        title: 'The Great Gatsby',
        author: 'F. Scott Fitzgerald',
        coverUrl: 'https://picsum.photos/300/400?random=9',
        url: 'https://www.gutenberg.org/files/64317/64317-0.txt',
    },
    {
        id: '1952',
        title: 'The Yellow Wallpaper',
        author: 'Charlotte Perkins Gilman',
        coverUrl: 'https://picsum.photos/300/400?random=27',
        url: 'https://www.gutenberg.org/files/1952/1952-0.txt',
    },
    {
        id: '76',
        title: 'Adventures of Huckleberry Finn',
        author: 'Mark Twain',
        coverUrl: 'https://picsum.photos/300/400?random=28',
        url: 'https://www.gutenberg.org/files/76/76-0.txt',
    },
    {
        id: '2542',
        title: 'A Doll\'s House',
        author: 'Henrik Ibsen',
        coverUrl: 'https://picsum.photos/300/400?random=29',
        url: 'https://www.gutenberg.org/files/2542/2542-0.txt',
    },
    {
        id: '16',
        title: 'The Awakening, and Selected Short Stories',
        author: 'Kate Chopin',
        coverUrl: 'https://picsum.photos/300/400?random=30',
        url: 'https://www.gutenberg.org/files/16/16-0.txt',
    },
    {
        id: '219',
        title: 'Heart of Darkness',
        author: 'Joseph Conrad',
        coverUrl: 'https://picsum.photos/300/400?random=31',
        url: 'https://www.gutenberg.org/files/219/219-0.txt',
    },
    {
        id: '43',
        title: 'The Strange Case of Dr. Jekyll and Mr. Hyde',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=32',
        url: 'https://www.gutenberg.org/files/43/43-0.txt',
    },
    {
        id: '1080',
        title: 'The Kama Sutra of Vatsyayana',
        author: 'Vatsyayana',
        coverUrl: 'https://picsum.photos/300/400?random=33',
        url: 'https://www.gutenberg.org/files/1080/1080-0.txt',
    },
    {
        id: '1259',
        title: 'Twenty Thousand Leagues under the Sea',
        author: 'Jules Verne',
        coverUrl: 'https://picsum.photos/300/400?random=34',
        url: 'https://www.gutenberg.org/files/1259/1259-0.txt',
    },
    {
        id: '46',
        title: 'A Christmas Carol',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=35',
        url: 'https://www.gutenberg.org/files/46/46-0.txt',
    },
    {
        id: '1400',
        title: 'Great Expectations',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=36',
        url: 'https://www.gutenberg.org/files/1400/1400-0.txt',
    },
    {
        id: '1232',
        title: 'The Prince',
        author: 'Niccolò Machiavelli',
        coverUrl: 'https://picsum.photos/300/400?random=37',
        url: 'https://www.gutenberg.org/files/1232/1232-0.txt',
    },
    {
        id: '30254',
        title: 'The Romance of Lust',
        author: 'Anonymous',
        coverUrl: 'https://picsum.photos/300/400?random=38',
        url: 'https://www.gutenberg.org/files/30254/30254-0.txt',
    },
    {
        id: '55',
        title: 'The Wonderful Wizard of Oz',
        author: 'L. Frank Baum',
        coverUrl: 'https://picsum.photos/300/400?random=39',
        url: 'https://www.gutenberg.org/files/55/55-0.txt',
    },
    {
        id: '215',
        title: 'The Call of the Wild',
        author: 'Jack London',
        coverUrl: 'https://picsum.photos/300/400?random=40',
        url: 'https://www.gutenberg.org/files/215/215-0.txt',
    },
    {
        id: '1184',
        title: 'The Count of Monte Cristo',
        author: 'Alexandre Dumas',
        coverUrl: 'https://picsum.photos/300/400?random=41',
        url: 'https://www.gutenberg.org/files/1184/1184-0.txt',
    },
    {
        id: '203',
        title: 'The Time Machine',
        author: 'H. G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=42',
        url: 'https://www.gutenberg.org/files/203/203-0.txt',
    },
    {
        id: '28054',
        title: 'The Island of Doctor Moreau',
        author: 'H. G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=43',
        url: 'https://www.gutenberg.org/files/28054/28054-0.txt',
    },
    {
        id: '67979',
        title: 'The Prophet',
        author: 'Kahlil Gibran',
        coverUrl: 'https://picsum.photos/300/400?random=44',
        url: 'https://www.gutenberg.org/files/67979/67979-0.txt',
    },
    {
        id: '135',
        title: 'Les Misérables',
        author: 'Victor Hugo',
        coverUrl: 'https://picsum.photos/300/400?random=45',
        url: 'https://www.gutenberg.org/files/135/135-0.txt',
    },
    {
        id: '1998',
        title: 'The Republic',
        author: 'Plato',
        coverUrl: 'https://picsum.photos/300/400?random=46',
        url: 'https://www.gutenberg.org/files/1998/1998-0.txt',
    },
    {
        id: '3207',
        title: 'Leviathan',
        author: 'Thomas Hobbes',
        coverUrl: 'https://picsum.photos/300/400?random=47',
        url: 'https://www.gutenberg.org/files/3207/3207-0.txt',
    },
    {
        id: '58585',
        title: 'The Communist Manifesto',
        author: 'Karl Marx and Friedrich Engels',
        coverUrl: 'https://picsum.photos/300/400?random=48',
        url: 'https://www.gutenberg.org/files/58585/58585-0.txt',
    },
    {
        id: '2814',
        title: 'Dubliners',
        author: 'James Joyce',
        coverUrl: 'https://picsum.photos/300/400?random=49',
        url: 'https://www.gutenberg.org/files/2814/2814-0.txt',
    },
    {
        id: '4280',
        title: 'A Portrait of the Artist as a Young Man',
        author: 'James Joyce',
        coverUrl: 'https://picsum.photos/300/400?random=50',
        url: 'https://www.gutenberg.org/files/4280/4280-0.txt',
    },
    {
        id: '103',
        title: 'Around the World in Eighty Days',
        author: 'Jules Verne',
        coverUrl: 'https://picsum.photos/300/400?random=51',
        url: 'https://www.gutenberg.org/files/103/103-0.txt',
    },
    {
        id: '829',
        title: 'Gulliver\'s Travels',
        author: 'Jonathan Swift',
        coverUrl: 'https://picsum.photos/300/400?random=52',
        url: 'https://www.gutenberg.org/files/829/829-0.txt',
    },
    {
        id: '209',
        title: 'The Turn of the Screw',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=53',
        url: 'https://www.gutenberg.org/files/209/209-0.txt',
    },
    {
        id: '145',
        title: 'Middlemarch',
        author: 'George Eliot',
        coverUrl: 'https://picsum.photos/300/400?random=54',
        url: 'https://www.gutenberg.org/files/145/145-0.txt',
    },
    {
        id: '1257',
        title: 'The Three Musketeers',
        author: 'Alexandre Dumas',
        coverUrl: 'https://picsum.photos/300/400?random=55',
        url: 'https://www.gutenberg.org/files/1257/1257-0.txt',
    },
    {
        id: '27827',
        title: 'The Brothers Karamazov',
        author: 'Fyodor Dostoevsky',
        coverUrl: 'https://picsum.photos/300/400?random=56',
        url: 'https://www.gutenberg.org/files/27827/27827-0.txt',
    },
    {
        id: '6130',
        title: 'The Iliad of Homer',
        author: 'Homer, translated by Alexander Pope',
        coverUrl: 'https://picsum.photos/300/400?random=57',
        url: 'https://www.gutenberg.org/files/6130/6130-0.txt'
    },
    {
        id: '1728',
        title: 'The Odyssey',
        author: 'Homer',
        coverUrl: 'https://picsum.photos/300/400?random=58',
        url: 'https://www.gutenberg.org/files/1728/1728-0.txt'
    },
    {
        id: '2852',
        title: 'The Hound of the Baskervilles',
        author: 'Arthur Conan Doyle',
        coverUrl: 'https://picsum.photos/300/400?random=59',
        url: 'https://www.gutenberg.org/files/2852/2852-0.txt'
    },
    {
        id: '205',
        title: 'Walden, and On The Duty Of Civil Disobedience',
        author: 'Henry David Thoreau',
        coverUrl: 'https://picsum.photos/300/400?random=60',
        url: 'https://www.gutenberg.org/files/205/205-0.txt'
    },
    {
        id: '16328',
        title: 'Beowulf',
        author: 'Anonymous',
        coverUrl: 'https://picsum.photos/300/400?random=61',
        url: 'https://www.gutenberg.org/files/16328/16328-0.txt'
    },
    {
        id: '1064',
        title: 'The Canterbury Tales, and Other Poems',
        author: 'Geoffrey Chaucer',
        coverUrl: 'https://picsum.photos/300/400?random=62',
        url: 'https://www.gutenberg.org/files/1064/1064-0.txt'
    },
    {
        id: '158',
        title: 'Emma',
        author: 'Jane Austen',
        coverUrl: 'https://picsum.photos/300/400?random=63',
        url: 'https://www.gutenberg.org/files/158/158-0.txt'
    },
    {
        id: '946',
        title: 'David Copperfield',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=64',
        url: 'https://www.gutenberg.org/files/946/946-0.txt'
    },
    {
        id: '14264',
        title: 'The Jungle Book',
        author: 'Rudyard Kipling',
        coverUrl: 'https://picsum.photos/300/400?random=65',
        url: 'https://www.gutenberg.org/files/14264/14264-0.txt'
    },
    {
        id: '244',
        title: 'A Study in Scarlet',
        author: 'Arthur Conan Doyle',
        coverUrl: 'https://picsum.photos/300/400?random=66',
        url: 'https://www.gutenberg.org/files/244/244-0.txt'
    },
    {
        id: '16389',
        title: 'The Memoirs of Sherlock Holmes',
        author: 'Arthur Conan Doyle',
        coverUrl: 'https://picsum.photos/300/400?random=67',
        url: 'https://www.gutenberg.org/files/16389/16389-0.txt'
    },
    {
        id: '8800',
        title: 'The Return of Sherlock Holmes',
        author: 'Arthur Conan Doyle',
        coverUrl: 'https://picsum.photos/300/400?random=68',
        url: 'https://www.gutenberg.org/files/8800/8800-0.txt'
    },
    {
        id: '108',
        title: 'The Sign of the Four',
        author: 'Arthur Conan Doyle',
        coverUrl: 'https://picsum.photos/300/400?random=69',
        url: 'https://www.gutenberg.org/files/108/108-0.txt'
    },
    {
        id: '23',
        title: 'The Narrative of the Life of Frederick Douglass',
        author: 'Frederick Douglass',
        coverUrl: 'https://picsum.photos/300/400?random=70',
        url: 'https://www.gutenberg.org/files/23/23-0.txt'
    },
    {
        id: '514',
        title: 'Little Women',
        author: 'Louisa May Alcott',
        coverUrl: 'https://picsum.photos/300/400?random=71',
        url: 'https://www.gutenberg.org/files/514/514-0.txt'
    },
    {
        id: '2641',
        title: 'A Room with a View',
        author: 'E. M. Forster',
        coverUrl: 'https://picsum.photos/300/400?random=72',
        url: 'https://www.gutenberg.org/files/2641/2641-0.txt'
    },
    {
        id: '394',
        title: 'Cranford',
        author: 'Elizabeth Gaskell',
        coverUrl: 'https://picsum.photos/300/400?random=73',
        url: 'https://www.gutenberg.org/files/394/394-0.txt'
    },
    {
        id: '4085',
        title: 'The Age of Innocence',
        author: 'Edith Wharton',
        coverUrl: 'https://picsum.photos/300/400?random=74',
        url: 'https://www.gutenberg.org/files/4085/4085-0.txt'
    },
    {
        id: '37106',
        title: 'The Secret Garden',
        author: 'Frances Hodgson Burnett',
        coverUrl: 'https://picsum.photos/300/400?random=75',
        url: 'https://www.gutenberg.org/files/37106/37106-0.txt'
    },
    {
        id: '2591',
        title: 'The House of Mirth',
        author: 'Edith Wharton',
        coverUrl: 'https://picsum.photos/300/400?random=76',
        url: 'https://www.gutenberg.org/files/2591/2591-0.txt'
    },
    {
        id: '19337',
        title: 'The Wind in the Willows',
        author: 'Kenneth Grahame',
        coverUrl: 'https://picsum.photos/300/400?random=77',
        url: 'https://www.gutenberg.org/files/19337/19337-0.txt'
    },
    {
        id: '2554',
        title: 'Crime and Punishment',
        author: 'Fyodor Dostoevsky',
        coverUrl: 'https://picsum.photos/300/400?random=78',
        url: 'https://www.gutenberg.org/files/2554/2554-0.txt'
    },
    {
        id: '61533',
        title: 'The Idiot',
        author: 'Fyodor Dostoevsky',
        coverUrl: 'https://picsum.photos/300/400?random=79',
        url: 'https://www.gutenberg.org/files/61533/61533-0.txt'
    },
    {
        id: '600',
        title: 'Notes from the Underground',
        author: 'Fyodor Dostoevsky',
        coverUrl: 'https://picsum.photos/300/400?random=80',
        url: 'https://www.gutenberg.org/files/600/600-0.txt'
    },
    {
        id: '1250',
        title: 'Madame Bovary',
        author: 'Gustave Flaubert',
        coverUrl: 'https://picsum.photos/300/400?random=81',
        url: 'https://www.gutenberg.org/files/1250/1250-0.txt'
    },
    {
        id: '161',
        title: 'Sense and Sensibility',
        author: 'Jane Austen',
        coverUrl: 'https://picsum.photos/300/400?random=82',
        url: 'https://www.gutenberg.org/files/161/161-0.txt'
    },
    {
        id: '105',
        title: 'Persuasion',
        author: 'Jane Austen',
        coverUrl: 'https://picsum.photos/300/400?random=83',
        url: 'https://www.gutenberg.org/files/105/105-0.txt'
    },
    {
        id: '141',
        title: 'Mansfield Park',
        author: 'Jane Austen',
        coverUrl: 'https://picsum.photos/300/400?random=84',
        url: 'https://www.gutenberg.org/files/141/141-0.txt'
    },
    {
        id: '1212',
        title: 'Northanger Abbey',
        author: 'Jane Austen',
        coverUrl: 'https://picsum.photos/300/400?random=85',
        url: 'https://www.gutenberg.org/files/1212/1212-0.txt'
    },
    {
        id: '20228',
        title: 'The Red Badge of Courage',
        author: 'Stephen Crane',
        coverUrl: 'https://picsum.photos/300/400?random=86',
        url: 'https://www.gutenberg.org/files/20228/20228-0.txt'
    },
    {
        id: '42',
        title: 'The Merry Adventures of Robin Hood',
        author: 'Howard Pyle',
        coverUrl: 'https://picsum.photos/300/400?random=87',
        url: 'https://www.gutenberg.org/files/42/42-0.txt'
    },
    {
        id: '41',
        title: 'The Legend of Sleepy Hollow',
        author: 'Washington Irving',
        coverUrl: 'https://picsum.photos/300/400?random=88',
        url: 'https://www.gutenberg.org/files/41/41-0.txt'
    },
    {
        id: '20',
        title: 'Paradise Lost',
        author: 'John Milton',
        coverUrl: 'https://picsum.photos/300/400?random=89',
        url: 'https://www.gutenberg.org/files/20/20-0.txt'
    },
    {
        id: '33',
        title: 'The Scarlet Pimpernel',
        author: 'Baroness Orczy',
        coverUrl: 'https://picsum.photos/300/400?random=90',
        url: 'https://www.gutenberg.org/files/33/33-0.txt'
    },
    {
        id: '82',
        title: 'Ivanhoe',
        author: 'Walter Scott',
        coverUrl: 'https://picsum.photos/300/400?random=91',
        url: 'https://www.gutenberg.org/files/82/82-0.txt'
    },
    {
        id: '2705',
        title: 'The Last of the Mohicans',
        author: 'James Fenimore Cooper',
        coverUrl: 'https://picsum.photos/300/400?random=92',
        url: 'https://www.gutenberg.org/files/2705/2705-0.txt'
    },
    {
        id: '1837',
        title: 'The Last Man',
        author: 'Mary Shelley',
        coverUrl: 'https://picsum.photos/300/400?random=93',
        url: 'https://www.gutenberg.org/files/1837/1837-0.txt'
    },
    {
        id: '521',
        title: 'The Life and Adventures of Robinson Crusoe',
        author: 'Daniel Defoe',
        coverUrl: 'https://picsum.photos/300/400?random=94',
        url: 'https://www.gutenberg.org/files/521/521-0.txt'
    },
    {
        id: '3825',
        title: 'Pygmalion',
        author: 'George Bernard Shaw',
        coverUrl: 'https://picsum.photos/300/400?random=95',
        url: 'https://www.gutenberg.org/files/3825/3825-0.txt'
    },
    {
        id: '1155',
        title: 'The Importance of Being Earnest',
        author: 'Oscar Wilde',
        coverUrl: 'https://picsum.photos/300/400?random=96',
        url: 'https://www.gutenberg.org/files/1155/1155-0.txt'
    },
    {
        id: '245',
        title: 'The Man Who Was Thursday',
        author: 'G.K. Chesterton',
        coverUrl: 'https://picsum.photos/300/400?random=97',
        url: 'https://www.gutenberg.org/files/245/245-0.txt'
    },
    {
        id: '1322',
        title: 'Leaves of Grass',
        author: 'Walt Whitman',
        coverUrl: 'https://picsum.photos/300/400?random=98',
        url: 'https://www.gutenberg.org/files/1322/1322-0.txt'
    },
    {
        id: '19942',
        title: 'The Divine Comedy',
        author: 'Dante Alighieri',
        coverUrl: 'https://picsum.photos/300/400?random=99',
        url: 'https://www.gutenberg.org/files/19942/19942-0.txt'
    },
    {
        id: '1513',
        title: 'Romeo and Juliet',
        author: 'William Shakespeare',
        coverUrl: 'https://picsum.photos/300/400?random=100',
        url: 'https://www.gutenberg.org/files/1513/1513-0.txt'
    },
    {
        id: '1533',
        title: 'Hamlet',
        author: 'William Shakespeare',
        coverUrl: 'https://picsum.photos/300/400?random=101',
        url: 'https://www.gutenberg.org/files/1533/1533-0.txt'
    },
    {
        id: '1524',
        title: 'Macbeth',
        author: 'William Shakespeare',
        coverUrl: 'https://picsum.photos/300/400?random=102',
        url: 'https://www.gutenberg.org/files/1524/1524-0.txt'
    },
    {
        id: '2265',
        title: 'Othello',
        author: 'William Shakespeare',
        coverUrl: 'https://picsum.photos/300/400?random=103',
        url: 'https://www.gutenberg.org/files/2265/2265-0.txt'
    },
    {
        id: '2267',
        title: 'The Tempest',
        author: 'William Shakespeare',
        coverUrl: 'https://picsum.photos/300/400?random=104',
        url: 'https://www.gutenberg.org/files/2267/2267-0.txt'
    },
    {
        id: '1795',
        title: 'A Midsummer Night\'s Dream',
        author: 'William Shakespeare',
        coverUrl: 'https://picsum.photos/300/400?random=105',
        url: 'https://www.gutenberg.org/files/1795/1795-0.txt'
    },
    {
        id: '2264',
        title: 'The Taming of the Shrew',
        author: 'William Shakespeare',
        coverUrl: 'https://picsum.photos/300/400?random=106',
        url: 'https://www.gutenberg.org/files/2264/2264-0.txt'
    },
    {
        id: '2266',
        title: 'The Merchant of Venice',
        author: 'William Shakespeare',
        coverUrl: 'https://picsum.photos/300/400?random=107',
        url: 'https://www.gutenberg.org/files/2266/2266-0.txt'
    },
    {
        id: '1787',
        title: 'King Lear',
        author: 'William Shakespeare',
        coverUrl: 'https://picsum.photos/300/400?random=108',
        url: 'https://www.gutenberg.org/files/1787/1787-0.txt'
    },
    {
        id: '23042',
        title: 'The Complete Works of William Shakespeare',
        author: 'William Shakespeare',
        coverUrl: 'https://picsum.photos/300/400?random=109',
        url: 'https://www.gutenberg.org/files/23042/23042-0.txt',
    },
    {
        id: '132',
        title: 'The Art of War',
        author: 'Sun Tzu',
        coverUrl: 'https://picsum.photos/300/400?random=110',
        url: 'https://www.gutenberg.org/files/132/132-0.txt',
    },
    {
        id: '5000',
        title: 'Thus Spake Zarathustra',
        author: 'Friedrich Nietzsche',
        coverUrl: 'https://picsum.photos/300/400?random=111',
        url: 'https://www.gutenberg.org/files/5000/5000-0.txt',
    },
    {
        id: '4363',
        title: 'Beyond Good and Evil',
        author: 'Friedrich Nietzsche',
        coverUrl: 'https://picsum.photos/300/400?random=112',
        url: 'https://www.gutenberg.org/files/4363/4363-0.txt',
    },
    {
        id: '2848',
        title: 'The Antichrist',
        author: 'Friedrich Nietzsche',
        coverUrl: 'https://picsum.photos/300/400?random=113',
        url: 'https://www.gutenberg.org/files/2848/2848-0.txt',
    },
    {
        id: '3800',
        title: 'The Critique of Pure Reason',
        author: 'Immanuel Kant',
        coverUrl: 'https://picsum.photos/300/400?random=114',
        url: 'https://www.gutenberg.org/files/3800/3800-0.txt',
    },
    {
        id: '574',
        title: 'The Souls of Black Folk',
        author: 'W. E. B. Du Bois',
        coverUrl: 'https://picsum.photos/300/400?random=115',
        url: 'https://www.gutenberg.org/files/574/574-0.txt',
    },
    {
        id: '32',
        title: 'Herland',
        author: 'Charlotte Perkins Gilman',
        coverUrl: 'https://picsum.photos/300/400?random=116',
        url: 'https://www.gutenberg.org/files/32/32-0.txt',
    },
    {
        id: '30',
        title: 'Little Women',
        author: 'Louisa May Alcott',
        coverUrl: 'https://picsum.photos/300/400?random=117',
        url: 'https://www.gutenberg.org/files/30/30-0.txt',
    },
    {
        id: '2708',
        title: 'The Pathfinder',
        author: 'James Fenimore Cooper',
        coverUrl: 'https://picsum.photos/300/400?random=118',
        url: 'https://www.gutenberg.org/files/2708/2708-0.txt',
    },
    {
        id: '940',
        title: 'The Deerslayer',
        author: 'James Fenimore Cooper',
        coverUrl: 'https://picsum.photos/300/400?random=119',
        url: 'https://www.gutenberg.org/files/940/940-0.txt',
    },
    {
        id: '18657',
        title: 'The Prairie',
        author: 'James Fenimore Cooper',
        coverUrl: 'https://picsum.photos/300/400?random=120',
        url: 'https://www.gutenberg.org/files/18657/18657-0.txt',
    },
    {
        id: '24022',
        title: 'The Pioneers',
        author: 'James Fenimore Cooper',
        coverUrl: 'https://picsum.photos/300/400?random=121',
        url: 'https://www.gutenberg.org/files/24022/24022-0.txt',
    },
    {
        id: '100',
        title: 'The Complete Works of William Shakespeare',
        author: 'William Shakespeare',
        coverUrl: 'https://picsum.photos/300/400?random=122',
        url: 'https://www.gutenberg.org/files/100/100-0.txt',
    },
    {
        id: '2595',
        title: 'The Innocents Abroad',
        author: 'Mark Twain',
        coverUrl: 'https://picsum.photos/300/400?random=123',
        url: 'https://www.gutenberg.org/files/2595/2595-0.txt',
    },
    {
        id: '18372',
        title: 'Roughing It',
        author: 'Mark Twain',
        coverUrl: 'https://picsum.photos/300/400?random=124',
        url: 'https://www.gutenberg.org/files/18372/18372-0.txt',
    },
    {
        id: '86',
        title: 'A Connecticut Yankee in King Arthur\'s Court',
        author: 'Mark Twain',
        coverUrl: 'https://picsum.photos/300/400?random=125',
        url: 'https://www.gutenberg.org/files/86/86-0.txt',
    },
    {
        id: '102',
        title: 'The Prince and the Pauper',
        author: 'Mark Twain',
        coverUrl: 'https://picsum.photos/300/400?random=126',
        url: 'https://www.gutenberg.org/files/102/102-0.txt',
    },
    {
        id: '2450',
        title: 'The Mysterious Stranger',
        author: 'Mark Twain',
        coverUrl: 'https://picsum.photos/300/400?random=127',
        url: 'https://www.gutenberg.org/files/2450/2450-0.txt',
    },
    {
        id: '3176',
        title: 'The American Claimant',
        author: 'Mark Twain',
        coverUrl: 'https://picsum.photos/300/400?random=128',
        url: 'https://www.gutenberg.org/files/3176/3176-0.txt',
    },
    {
        id: '3177',
        title: 'The £1,000,000 Bank-Note',
        author: 'Mark Twain',
        coverUrl: 'https://picsum.photos/300/400?random=129',
        url: 'https://www.gutenberg.org/files/3177/3177-0.txt',
    },
    {
        id: '3190',
        title: 'The Tragedy of Pudd\'nhead Wilson',
        author: 'Mark Twain',
        coverUrl: 'https://picsum.photos/300/400?random=130',
        url: 'https://www.gutenberg.org/files/3190/3190-0.txt',
    },
    {
        id: '2890',
        title: 'Following the Equator',
        author: 'Mark Twain',
        coverUrl: 'https://picsum.photos/300/400?random=131',
        url: 'https://www.gutenberg.org/files/2890/2890-0.txt',
    },
    {
        id: '142',
        title: 'Hard Times',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=132',
        url: 'https://www.gutenberg.org/files/142/142-0.txt',
    },
    {
        id: '580',
        title: 'The Pickwick Papers',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=133',
        url: 'https://www.gutenberg.org/files/580/580-0.txt',
    },
    {
        id: '730',
        title: 'Oliver Twist',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=134',
        url: 'https://www.gutenberg.org/files/730/730-0.txt',
    },
    {
        id: '882',
        title: 'Nicholas Nickleby',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=135',
        url: 'https://www.gutenberg.org/files/882/882-0.txt',
    },
    {
        id: '675',
        title: 'The Old Curiosity Shop',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=136',
        url: 'https://www.gutenberg.org/files/675/675-0.txt',
    },
    {
        id: '700',
        title: 'Barnaby Rudge',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=137',
        url: 'https://www.gutenberg.org/files/700/700-0.txt',
    },
    {
        id: '821',
        title: 'Martin Chuzzlewit',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=138',
        url: 'https://www.gutenberg.org/files/821/821-0.txt',
    },
    {
        id: '967',
        title: 'Dombey and Son',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=139',
        url: 'https://www.gutenberg.org/files/967/967-0.txt',
    },
    {
        id: '564',
        title: 'Bleak House',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=140',
        url: 'https://www.gutenberg.org/files/564/564-0.txt',
    },
    {
        id: '968',
        title: 'Little Dorrit',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=141',
        url: 'https://www.gutenberg.org/files/968/968-0.txt',
    },
    {
        id: '786',
        title: 'Our Mutual Friend',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=142',
        url: 'https://www.gutenberg.org/files/786/786-0.txt',
    },
    {
        id: '963',
        title: 'The Mystery of Edwin Drood',
        author: 'Charles Dickens',
        coverUrl: 'https://picsum.photos/300/400?random=143',
        url: 'https://www.gutenberg.org/files/963/963-0.txt',
    },
    {
        id: '204',
        title: 'The Invisible Man',
        author: 'H. G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=144',
        url: 'https://www.gutenberg.org/files/204/204-0.txt',
    },
    {
        id: '35',
        title: 'The Time Machine',
        author: 'H. G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=145',
        url: 'https://www.gutenberg.org/files/35/35-0.txt',
    },
    {
        id: '159',
        title: 'The War of the Worlds',
        author: 'H. G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=146',
        url: 'https://www.gutenberg.org/files/159/159-0.txt',
    },
    {
        id: '5230',
        title: 'The First Men in the Moon',
        author: 'H. G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=147',
        url: 'https://www.gutenberg.org/files/5230/5230-0.txt',
    },
    {
        id: '1187',
        title: 'The Food of the Gods and How It Came to Earth',
        author: 'H. G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=148',
        url: 'https://www.gutenberg.org/files/1187/1187-0.txt',
    },
    {
        id: '59774',
        title: 'The Shape of Things to Come',
        author: 'H. G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=149',
        url: 'https://www.gutenberg.org/files/59774/59774-0.txt',
    },
    {
        id: '2236',
        title: 'The History of Mr. Polly',
        author: 'H. G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=150',
        url: 'https://www.gutenberg.org/files/2236/2236-0.txt',
    },
    {
        id: '1169',
        title: 'Kipps: The Story of a Simple Soul',
        author: 'H. G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=151',
        url: 'https://www.gutenberg.org/files/1169/1169-0.txt',
    },
    {
        id: '59775',
        title: 'The World Set Free',
        author: 'H. G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=152',
        url: 'https://www.gutenberg.org/files/59775/59775-0.txt',
    },
    {
        id: '644',
        title: 'The Sleeper Awakes',
        author: 'H. G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=153',
        url: 'https://www.gutenberg.org/files/644/644-0.txt',
    },
    {
        id: '2247',
        title: 'The New Machiavelli',
        author: 'H. G. Wells',
        coverUrl: 'https://picsum.photos/300/400?random=154',
        url: 'https://www.gutenberg.org/files/2247/2247-0.txt',
    },
    {
        id: '155',
        title: 'The Secret Agent: A Simple Tale',
        author: 'Joseph Conrad',
        coverUrl: 'https://picsum.photos/300/400?random=155',
        url: 'https://www.gutenberg.org/files/155/155-0.txt',
    },
    {
        id: '220',
        title: 'Lord Jim',
        author: 'Joseph Conrad',
        coverUrl: 'https://picsum.photos/300/400?random=156',
        url: 'https://www.gutenberg.org/files/220/220-0.txt',
    },
    {
        id: '95',
        title: 'Nostromo: A Tale of the Seaboard',
        author: 'Joseph Conrad',
        coverUrl: 'https://picsum.photos/300/400?random=157',
        url: 'https://www.gutenberg.org/files/95/95-0.txt',
    },
    {
        id: '2025',
        title: 'Under Western Eyes',
        author: 'Joseph Conrad',
        coverUrl: 'https://picsum.photos/300/400?random=158',
        url: 'https://www.gutenberg.org/files/2025/2025-0.txt',
    },
    {
        id: '499',
        title: 'The Rover',
        author: 'Joseph Conrad',
        coverUrl: 'https://picsum.photos/300/400?random=159',
        url: 'https://www.gutenberg.org/files/499/499-0.txt',
    },
    {
        id: '525',
        title: 'The Arrow of Gold',
        author: 'Joseph Conrad',
        coverUrl: 'https://picsum.photos/300/400?random=160',
        url: 'https://www.gutenberg.org/files/525/525-0.txt',
    },
    {
        id: '526',
        title: 'Victory: An Island Tale',
        author: 'Joseph Conrad',
        coverUrl: 'https://picsum.photos/300/400?random=161',
        url: 'https://www.gutenberg.org/files/526/526-0.txt',
    },
    {
        id: '524',
        title: 'Chance',
        author: 'Joseph Conrad',
        coverUrl: 'https://picsum.photos/300/400?random=162',
        url: 'https://www.gutenberg.org/files/524/524-0.txt',
    },
    {
        id: '475',
        title: 'The Shadow Line',
        author: 'Joseph Conrad',
        coverUrl: 'https://picsum.photos/300/400?random=163',
        url: 'https://www.gutenberg.org/files/475/475-0.txt',
    },
    {
        id: '2014',
        title: 'A Personal Record',
        author: 'Joseph Conrad',
        coverUrl: 'https://picsum.photos/300/400?random=164',
        url: 'https://www.gutenberg.org/files/2014/2014-0.txt',
    },
    {
        id: '185',
        title: 'The Voyage Out',
        author: 'Virginia Woolf',
        coverUrl: 'https://picsum.photos/300/400?random=165',
        url: 'https://www.gutenberg.org/files/185/185-0.txt',
    },
    {
        id: '67702',
        title: 'Mrs Dalloway',
        author: 'Virginia Woolf',
        coverUrl: 'https://picsum.photos/300/400?random=166',
        url: 'https://www.gutenberg.org/files/67702/67702-0.txt',
    },
    {
        id: '67918',
        title: 'To the Lighthouse',
        author: 'Virginia Woolf',
        coverUrl: 'https://picsum.photos/300/400?random=167',
        url: 'https://www.gutenberg.org/files/67918/67918-0.txt',
    },
    {
        id: '67926',
        title: 'Orlando: A Biography',
        author: 'Virginia Woolf',
        coverUrl: 'https://picsum.photos/300/400?random=168',
        url: 'https://www.gutenberg.org/files/67926/67926-0.txt',
    },
    {
        id: '67980',
        title: 'A Room of One\'s Own',
        author: 'Virginia Woolf',
        coverUrl: 'https://picsum.photos/300/400?random=169',
        url: 'https://www.gutenberg.org/files/67980/67980-0.txt',
    },
    {
        id: '67927',
        title: 'The Waves',
        author: 'Virginia Woolf',
        coverUrl: 'https://picsum.photos/300/400?random=170',
        url: 'https://www.gutenberg.org/files/67927/67927-0.txt',
    },
    {
        id: '1589',
        title: 'Night and Day',
        author: 'Virginia Woolf',
        coverUrl: 'https://picsum.photos/300/400?random=171',
        url: 'https://www.gutenberg.org/files/1589/1589-0.txt',
    },
    {
        id: '2863',
        title: 'Jacob\'s Room',
        author: 'Virginia Woolf',
        coverUrl: 'https://picsum.photos/300/400?random=172',
        url: 'https://www.gutenberg.org/files/2863/2863-0.txt',
    },
    {
        id: '4079',
        title: 'The Common Reader',
        author: 'Virginia Woolf',
        coverUrl: 'https://picsum.photos/300/400?random=173',
        url: 'https://www.gutenberg.org/files/4079/4079-0.txt',
    },
    {
        id: '3335',
        title: 'The Second Common Reader',
        author: 'Virginia Woolf',
        coverUrl: 'https://picsum.photos/300/400?random=174',
        url: 'https://www.gutenberg.org/files/3335/3335-0.txt',
    },
    {
        id: '2875',
        title: 'Monday or Tuesday',
        author: 'Virginia Woolf',
        coverUrl: 'https://picsum.photos/300/400?random=175',
        url: 'https://www.gutenberg.org/files/2875/2875-0.txt',
    },
    {
        id: '121',
        title: 'Kidnapped',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=176',
        url: 'https://www.gutenberg.org/files/121/121-0.txt',
    },
    {
        id: '421',
        title: 'The Black Arrow',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=177',
        url: 'https://www.gutenberg.org/files/421/421-0.txt',
    },
    {
        id: '75',
        title: 'The Master of Ballantrae',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=178',
        url: 'https://www.gutenberg.org/files/75/75-0.txt',
    },
    {
        id: '3093',
        title: 'Catriona',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=179',
        url: 'https://www.gutenberg.org/files/3093/3093-0.txt',
    },
    {
        id: '417',
        title: 'The Wrecker',
        author: 'Robert Louis Stevenson and Lloyd Osbourne',
        coverUrl: 'https://picsum.photos/300/400?random=180',
        url: 'https://www.gutenberg.org/files/417/417-0.txt',
    },
    {
        id: '535',
        title: 'The Ebb-Tide',
        author: 'Robert Louis Stevenson and Lloyd Osbourne',
        coverUrl: 'https://picsum.photos/300/400?random=181',
        url: 'https://www.gutenberg.org/files/535/535-0.txt',
    },
    {
        id: '536',
        title: 'Island Nights\' Entertainments',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=182',
        url: 'https://www.gutenberg.org/files/536/536-0.txt',
    },
    {
        id: '1249',
        title: 'An Inland Voyage',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=183',
        url: 'https://www.gutenberg.org/files/1249/1249-0.txt',
    },
    {
        id: '505',
        title: 'Travels with a Donkey in the Cévennes',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=184',
        url: 'https://www.gutenberg.org/files/505/505-0.txt',
    },
    {
        id: '416',
        title: 'Virginibus Puerisque, and Other Papers',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=185',
        url: 'https://www.gutenberg.org/files/416/416-0.txt',
    },
    {
        id: '447',
        title: 'The New Arabian Nights',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=186',
        url: 'https://www.gutenberg.org/files/447/447-0.txt',
    },
    {
        id: '415',
        title: 'The Merry Men, and Other Tales and Fables',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=187',
        url: 'https://www.gutenberg.org/files/415/415-0.txt',
    },
    {
        id: '307',
        title: 'The Dynamiter',
        author: 'Robert Louis Stevenson and Fanny Van de Grift Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=188',
        url: 'https://www.gutenberg.org/files/307/307-0.txt',
    },
    {
        id: '298',
        title: 'The Wrong Box',
        author: 'Robert Louis Stevenson and Lloyd Osbourne',
        coverUrl: 'https://picsum.photos/300/400?random=189',
        url: 'https://www.gutenberg.org/files/298/298-0.txt',
    },
    {
        id: '299',
        title: 'A Footnote to History: Eight Years of Trouble in Samoa',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=190',
        url: 'https://www.gutenberg.org/files/299/299-0.txt',
    },
    {
        id: '348',
        title: 'The Silverado Squatters',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=191',
        url: 'https://www.gutenberg.org/files/348/348-0.txt',
    },
    {
        id: '297',
        title: 'Across the Plains, with Other Memories and Essays',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=192',
        url: 'https://www.gutenberg.org/files/297/297-0.txt',
    },
    {
        id: '208',
        title: 'Familiar Studies of Men and Books',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=193',
        url: 'https://www.gutenberg.org/files/208/208-0.txt',
    },
    {
        id: '296',
        title: 'Memories and Portraits',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=194',
        url: 'https://www.gutenberg.org/files/296/296-0.txt',
    },
    {
        id: '295',
        title: 'A Child\'s Garden of Verses',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=195',
        url: 'https://www.gutenberg.org/files/295/295-0.txt',
    },
    {
        id: '382',
        title: 'Underwoods',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=196',
        url: 'https://www.gutenberg.org/files/382/382-0.txt',
    },
    {
        id: '503',
        title: 'Ballads',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=197',
        url: 'https://www.gutenberg.org/files/503/503-0.txt',
    },
    {
        id: '30990',
        title: 'Songs of Travel, and Other Verses',
        author: 'Robert Louis Stevenson',
        coverUrl: 'https://picsum.photos/300/400?random=198',
        url: 'https://www.gutenberg.org/files/30990/30990-0.txt',
    },
    {
        id: '228',
        title: 'The Man in the Iron Mask',
        author: 'Alexandre Dumas',
        coverUrl: 'https://picsum.photos/300/400?random=199',
        url: 'https://www.gutenberg.org/files/228/228-0.txt',
    },
    {
        id: '1258',
        title: 'Twenty Years After',
        author: 'Alexandre Dumas',
        coverUrl: 'https://picsum.photos/300/400?random=200',
        url: 'https://www.gutenberg.org/files/1258/1258-0.txt',
    },
    {
        id: '2680',
        title: 'The Vicomte de Bragelonne',
        author: 'Alexandre Dumas',
        coverUrl: 'https://picsum.photos/300/400?random=201',
        url: 'https://www.gutenberg.org/files/2680/2680-0.txt',
    },
    {
        id: '1013',
        title: 'The Black Tulip',
        author: 'Alexandre Dumas',
        coverUrl: 'https://picsum.photos/300/400?random=202',
        url: 'https://www.gutenberg.org/files/1013/1013-0.txt',
    },
    {
        id: '965',
        title: 'The Queen\'s Necklace',
        author: 'Alexandre Dumas',
        coverUrl: 'https://picsum.photos/300/400?random=203',
        url: 'https://www.gutenberg.org/files/965/965-0.txt',
    },
    {
        id: '1769',
        title: 'The Man Who Laughs',
        author: 'Victor Hugo',
        coverUrl: 'https://picsum.photos/300/400?random=204',
        url: 'https://www.gutenberg.org/files/1769/1769-0.txt',
    },
    {
        id: '2527',
        title: 'The Toilers of the Sea',
        author: 'Victor Hugo',
        coverUrl: 'https://picsum.photos/300/400?random=205',
        url: 'https://www.gutenberg.org/files/2527/2527-0.txt',
    },
    {
        id: '125',
        title: 'The Hunchback of Notre Dame',
        author: 'Victor Hugo',
        coverUrl: 'https://picsum.photos/300/400?random=206',
        url: 'https://www.gutenberg.org/files/125/125-0.txt',
    },
    {
        id: '20203',
        title: 'The Meditations',
        author: 'Marcus Aurelius',
        coverUrl: 'https://picsum.photos/300/400?random=207',
        url: 'https://www.gutenberg.org/files/20203/20203-0.txt',
    },
    {
        id: '10681',
        title: 'The Republic of Plato',
        author: 'Plato',
        coverUrl: 'https://picsum.photos/300/400?random=208',
        url: 'https://www.gutenberg.org/files/10681/10681-0.txt',
    },
    {
        id: '1974',
        title: 'The Nicomachean Ethics of Aristotle',
        author: 'Aristotle',
        coverUrl: 'https://picsum.photos/300/400?random=209',
        url: 'https://www.gutenberg.org/files/1974/1974-0.txt',
    },
    {
        id: '67837',
        title: 'Poetics',
        author: 'Aristotle',
        coverUrl: 'https://picsum.photos/300/400?random=210',
        url: 'https://www.gutenberg.org/files/67837/67837-0.txt',
    },
    {
        id: '2262',
        title: 'Antigone',
        author: 'Sophocles',
        coverUrl: 'https://picsum.photos/300/400?random=211',
        url: 'https://www.gutenberg.org/files/2262/2262-0.txt',
    },
    {
        id: '31',
        title: 'Oedipus Rex',
        author: 'Sophocles',
        coverUrl: 'https://picsum.photos/300/400?random=212',
        url: 'https://www.gutenberg.org/files/31/31-0.txt',
    },
    {
        id: '8161',
        title: 'The Frogs',
        author: 'Aristophanes',
        coverUrl: 'https://picsum.photos/300/400?random=213',
        url: 'https://www.gutenberg.org/files/8161/8161-0.txt',
    },
    {
        id: '7700',
        title: 'Lysistrata',
        author: 'Aristophanes',
        coverUrl: 'https://picsum.photos/300/400?random=214',
        url: 'https://www.gutenberg.org/files/7700/7700-0.txt',
    },
    {
        id: '1497',
        title: 'The History of the Peloponnesian War',
        author: 'Thucydides',
        coverUrl: 'https://picsum.photos/300/400?random=215',
        url: 'https://www.gutenberg.org/files/1497/1497-0.txt',
    },
    {
        id: '2238',
        title: 'The Histories',
        author: 'Herodotus',
        coverUrl: 'https://picsum.photos/300/400?random=216',
        url: 'https://www.gutenberg.org/files/2238/2238-0.txt',
    },
    {
        id: '1159',
        title: 'The Aeneid',
        author: 'Virgil',
        coverUrl: 'https://picsum.photos/300/400?random=217',
        url: 'https://www.gutenberg.org/files/1159/1159-0.txt',
    },
    {
        id: '875',
        title: 'The Metamorphoses',
        author: 'Ovid',
        coverUrl: 'https://picsum.photos/300/400?random=218',
        url: 'https://www.gutenberg.org/files/875/875-0.txt',
    },
    {
        id: '5231',
        title: 'On the Nature of Things',
        author: 'Lucretius',
        coverUrl: 'https://picsum.photos/300/400?random=219',
        url: 'https://www.gutenberg.org/files/5231/5231-0.txt',
    },
    {
        id: '10661',
        title: 'The Lives of the Twelve Caesars',
        author: 'Suetonius',
        coverUrl: 'https://picsum.photos/300/400?random=220',
        url: 'https://www.gutenberg.org/files/10661/10661-0.txt',
    },
    {
        id: '10675',
        title: 'The Annals',
        author: 'Tacitus',
        coverUrl: 'https://picsum.photos/300/400?random=221',
        url: 'https://www.gutenberg.org/files/10675/10675-0.txt',
    },
    {
        id: '6763',
        title: 'The Consolation of Philosophy',
        author: 'Boethius',
        coverUrl: 'https://picsum.photos/300/400?random=222',
        url: 'https://www.gutenberg.org/files/6763/6763-0.txt',
    },
    {
        id: '3621',
        title: 'The Decameron',
        author: 'Giovanni Boccaccio',
        coverUrl: 'https://picsum.photos/300/400?random=223',
        url: 'https://www.gutenberg.org/files/3621/3621-0.txt',
    },
    {
        id: '446',
        title: 'The Praise of Folly',
        author: 'Erasmus',
        coverUrl: 'https://picsum.photos/300/400?random=224',
        url: 'https://www.gutenberg.org/files/446/446-0.txt',
    },
    {
        id: '2023',
        title: 'Utopia',
        author: 'Thomas More',
        coverUrl: 'https://picsum.photos/300/400?random=225',
        url: 'https://www.gutenberg.org/files/2023/2023-0.txt',
    },
    {
        id: '4281',
        title: 'The Essays of Montaigne',
        author: 'Michel de Montaigne',
        coverUrl: 'https://picsum.photos/300/400?random=226',
        url: 'https://www.gutenberg.org/files/4281/4281-0.txt',
    },
    {
        id: '3832',
        title: 'The History of the Decline and Fall of the Roman Empire',
        author: 'Edward Gibbon',
        coverUrl: 'https://picsum.photos/300/400?random=227',
        url: 'https://www.gutenberg.org/files/3832/3832-0.txt',
    },
    {
        id: '777',
        title: 'The Wealth of Nations',
        author: 'Adam Smith',
        coverUrl: 'https://picsum.photos/300/400?random=228',
        url: 'https://www.gutenberg.org/files/777/777-0.txt',
    },
    {
        id: '5001',
        title: 'The Social Contract',
        author: 'Jean-Jacques Rousseau',
        coverUrl: 'https://picsum.photos/300/400?random=229',
        url: 'https://www.gutenberg.org/files/5001/5001-0.txt',
    },
    {
        id: '3200',
        title: 'Candide',
        author: 'Voltaire',
        coverUrl: 'https://picsum.photos/300/400?random=230',
        url: 'https://www.gutenberg.org/files/3200/3200-0.txt',
    },
    {
        id: '10887',
        title: 'Faust',
        author: 'Johann Wolfgang von Goethe',
        coverUrl: 'https://picsum.photos/300/400?random=231',
        url: 'https://www.gutenberg.org/files/10887/10887-0.txt',
    },
    {
        id: '408',
        title: 'The Sorrows of Young Werther',
        author: 'Johann Wolfgang von Goethe',
        coverUrl: 'https://picsum.photos/300/400?random=232',
        url: 'https://www.gutenberg.org/files/408/408-0.txt',
    },
    {
        id: '2989',
        title: 'The Robbers',
        author: 'Friedrich Schiller',
        coverUrl: 'https://picsum.photos/300/400?random=233',
        url: 'https://www.gutenberg.org/files/2989/2989-0.txt',
    },
    {
        id: '6762',
        title: 'Don Carlos',
        author: 'Friedrich Schiller',
        coverUrl: 'https://picsum.photos/300/400?random=234',
        url: 'https://www.gutenberg.org/files/6762/6762-0.txt',
    },
    {
        id: '6761',
        title: 'The Maid of Orleans',
        author: 'Friedrich Schiller',
        coverUrl: 'https://picsum.photos/300/400?random=235',
        url: 'https://www.gutenberg.org/files/6761/6761-0.txt',
    },
    {
        id: '5197',
        title: 'Eugene Onegin',
        author: 'Aleksandr Pushkin',
        coverUrl: 'https://picsum.photos/300/400?random=236',
        url: 'https://www.gutenberg.org/files/5197/5197-0.txt',
    },
    {
        id: '3603',
        title: 'Dead Souls',
        author: 'Nikolai Gogol',
        coverUrl: 'https://picsum.photos/300/400?random=237',
        url: 'https://www.gutenberg.org/files/3603/3603-0.txt',
    },
    {
        id: '2105',
        title: 'Fathers and Sons',
        author: 'Ivan Turgenev',
        coverUrl: 'https://picsum.photos/300/400?random=238',
        url: 'https://www.gutenberg.org/files/2105/2105-0.txt',
    },
    {
        id: '2805',
        title: 'The Cherry Orchard',
        author: 'Anton Chekhov',
        coverUrl: 'https://picsum.photos/300/400?random=239',
        url: 'https://www.gutenberg.org/files/2805/2805-0.txt',
    },
    {
        id: '702',
        title: 'The Seagull',
        author: 'Anton Chekhov',
        coverUrl: 'https://picsum.photos/300/400?random=240',
        url: 'https://www.gutenberg.org/files/702/702-0.txt',
    },
    {
        id: '701',
        title: 'Uncle Vanya',
        author: 'Anton Chekhov',
        coverUrl: 'https://picsum.photos/300/400?random=241',
        url: 'https://www.gutenberg.org/files/701/701-0.txt',
    },
    {
        id: '1753',
        title: 'The Three Sisters',
        author: 'Anton Chekhov',
        coverUrl: 'https://picsum.photos/300/400?random=242',
        url: 'https://www.gutenberg.org/files/1753/1753-0.txt',
    },
    {
        id: '2634',
        title: 'The Bet',
        author: 'Anton Chekhov',
        coverUrl: 'https://picsum.photos/300/400?random=243',
        url: 'https://www.gutenberg.org/files/2634/2634-0.txt',
    },
    {
        id: '217',
        title: 'The Red and the Black',
        author: 'Stendhal',
        coverUrl: 'https://picsum.photos/300/400?random=244',
        url: 'https://www.gutenberg.org/files/217/217-0.txt',
    },
    {
        id: '2007',
        title: 'Père Goriot',
        author: 'Honoré de Balzac',
        coverUrl: 'https://picsum.photos/300/400?random=245',
        url: 'https://www.gutenberg.org/files/2007/2007-0.txt',
    },
    {
        id: '1241',
        title: 'Cousin Bette',
        author: 'Honoré de Balzac',
        coverUrl: 'https://picsum.photos/300/400?random=246',
        url: 'https://www.gutenberg.org/files/1241/1241-0.txt',
    },
    {
        id: '528',
        title: 'The Flowers of Evil',
        author: 'Charles Baudelaire',
        coverUrl: 'https://picsum.photos/300/400?random=247',
        url: 'https://www.gutenberg.org/files/528/528-0.txt',
    },
    {
        id: '1992',
        title: 'Swann\'s Way',
        author: 'Marcel Proust',
        coverUrl: 'https://picsum.photos/300/400?random=248',
        url: 'https://www.gutenberg.org/files/1992/1992-0.txt',
    },
    {
        id: '6765',
        title: 'The Stranger',
        author: 'Albert Camus',
        coverUrl: 'https://picsum.photos/300/400?random=249',
        url: 'https://www.gutenberg.org/files/6765/6765-0.txt',
    },
    {
        id: '1240',
        title: 'The Plague',
        author: 'Albert Camus',
        coverUrl: 'https://picsum.photos/300/400?random=250',
        url: 'https://www.gutenberg.org/files/1240/1240-0.txt',
    },
    {
        id: '3203',
        title: 'The Myth of Sisyphus',
        author: 'Albert Camus',
        coverUrl: 'https://picsum.photos/300/400?random=251',
        url: 'https://www.gutenberg.org/files/3203/3203-0.txt',
    },
    {
        id: '3204',
        title: 'The Rebel',
        author: 'Albert Camus',
        coverUrl: 'https://picsum.photos/300/400?random=252',
        url: 'https://www.gutenberg.org/files/3204/3204-0.txt',
    },
    {
        id: '3193',
        title: 'Nausea',
        author: 'Jean-Paul Sartre',
        coverUrl: 'https://picsum.photos/300/400?random=253',
        url: 'https://www.gutenberg.org/files/3193/3193-0.txt',
    },
    {
        id: '590',
        title: 'The Trial',
        author: 'Franz Kafka',
        coverUrl: 'https://picsum.photos/300/400?random=254',
        url: 'https://www.gutenberg.org/files/590/590-0.txt',
    },
    {
        id: '7849',
        title: 'The Castle',
        author: 'Franz Kafka',
        coverUrl: 'https://picsum.photos/300/400?random=255',
        url: 'https://www.gutenberg.org/files/7849/7849-0.txt',
    },
    {
        id: '3202',
        title: 'Siddhartha',
        author: 'Hermann Hesse',
        coverUrl: 'https://picsum.photos/300/400?random=256',
        url: 'https://www.gutenberg.org/files/3202/3202-0.txt',
    },
    {
        id: '2500',
        title: 'Steppenwolf',
        author: 'Hermann Hesse',
        coverUrl: 'https://picsum.photos/300/400?random=257',
        url: 'https://www.gutenberg.org/files/2500/2500-0.txt',
    },
    {
        id: '2501',
        title: 'The Glass Bead Game',
        author: 'Hermann Hesse',
        coverUrl: 'https://picsum.photos/300/400?random=258',
        url: 'https://www.gutenberg.org/files/2501/2501-0.txt',
    },
    {
        id: '2115',
        title: 'Demian',
        author: 'Hermann Hesse',
        coverUrl: 'https://picsum.photos/300/400?random=259',
        url: 'https://www.gutenberg.org/files/2115/2115-0.txt',
    },
    {
        id: '2113',
        title: 'Narcissus and Goldmund',
        author: 'Hermann Hesse',
        coverUrl: 'https://picsum.photos/300/400?random=260',
        url: 'https://www.gutenberg.org/files/2113/2113-0.txt',
    },
    {
        id: '4364',
        title: 'The Magic Mountain',
        author: 'Thomas Mann',
        coverUrl: 'https://picsum.photos/300/400?random=261',
        url: 'https://www.gutenberg.org/files/4364/4364-0.txt',
    },
    {
        id: '6766',
        title: 'Death in Venice',
        author: 'Thomas Mann',
        coverUrl: 'https://picsum.photos/300/400?random=262',
        url: 'https://www.gutenberg.org/files/6766/6766-0.txt',
    },
    {
        id: '2345',
        title: 'Buddenbrooks',
        author: 'Thomas Mann',
        coverUrl: 'https://picsum.photos/300/400?random=263',
        url: 'https://www.gutenberg.org/files/2345/2345-0.txt',
    },
    {
        id: '4900',
        title: 'The Adventures of Pinocchio',
        author: 'Carlo Collodi',
        coverUrl: 'https://picsum.photos/300/400?random=264',
        url: 'https://www.gutenberg.org/files/4900/4900-0.txt',
    },
    {
        id: '19336',
        title: 'The Little Prince',
        author: 'Antoine de Saint-Exupéry',
        coverUrl: 'https://picsum.photos/300/400?random=265',
        url: 'https://www.gutenberg.org/files/19336/19336-0.txt',
    },
    {
        id: '2428',
        title: 'The Jungle',
        author: 'Upton Sinclair',
        coverUrl: 'https://picsum.photos/300/400?random=266',
        url: 'https://www.gutenberg.org/files/2428/2428-0.txt',
    },
    {
        id: '12',
        title: 'Through the Looking-Glass',
        author: 'Lewis Carroll',
        coverUrl: 'https://picsum.photos/300/400?random=267',
        url: 'https://www.gutenberg.org/files/12/12-0.txt',
    },
    {
        id: '28885',
        title: 'The Hunting of the Snark',
        author: 'Lewis Carroll',
        coverUrl: 'https://picsum.photos/300/400?random=268',
        url: 'https://www.gutenberg.org/files/28885/28885-0.txt',
    },
    {
        id: '42671',
        title: 'The Wonderful Wizard of Oz',
        author: 'L. Frank Baum',
        coverUrl: 'https://picsum.photos/300/400?random=269',
        url: 'https://www.gutenberg.org/files/42671/42671-0.txt',
    },
    {
        id: '43936',
        title: 'The Marvelous Land of Oz',
        author: 'L. Frank Baum',
        coverUrl: 'https://picsum.photos/300/400?random=270',
        url: 'https://www.gutenberg.org/files/43936/43936-0.txt',
    },
    {
        id: '420',
        title: 'Ozma of Oz',
        author: 'L. Frank Baum',
        coverUrl: 'https://picsum.photos/300/400?random=271',
        url: 'https://www.gutenberg.org/files/420/420-0.txt',
    },
    {
        id: '4352',
        title: 'Dorothy and the Wizard in Oz',
        author: 'L. Frank Baum',
        coverUrl: 'https://picsum.photos/300/400?random=272',
        url: 'https://www.gutenberg.org/files/4352/4352-0.txt',
    },
    {
        id: '22566',
        title: 'The Road to Oz',
        author: 'L. Frank Baum',
        coverUrl: 'https://picsum.photos/300/400?random=273',
        url: 'https://www.gutenberg.org/files/22566/22566-0.txt',
    },
    {
        id: '23528',
        title: 'The Emerald City of Oz',
        author: 'L. Frank Baum',
        coverUrl: 'https://picsum.photos/300/400?random=274',
        url: 'https://www.gutenberg.org/files/23528/23528-0.txt',
    },
    {
        id: '23691',
        title: 'The Patchwork Girl of Oz',
        author: 'L. Frank Baum',
        coverUrl: 'https://picsum.photos/300/400?random=275',
        url: 'https://www.gutenberg.org/files/23691/23691-0.txt',
    },
    {
        id: '484',
        title: 'Tik-Tok of Oz',
        author: 'L. Frank Baum',
        coverUrl: 'https://picsum.photos/300/400?random=276',
        url: 'https://www.gutenberg.org/files/484/484-0.txt',
    },
    {
        id: '24328',
        title: 'The Scarecrow of Oz',
        author: 'L. Frank Baum',
        coverUrl: 'https://picsum.photos/300/400?random=277',
        url: 'https://www.gutenberg.org/files/24328/24328-0.txt',
    },
    {
        id: '24634',
        title: 'Rinkitink in Oz',
        author: 'L. Frank Baum',
        coverUrl: 'https://picsum.photos/300/400?random=278',
        url: 'https://www.gutenberg.org/files/24634/24634-0.txt',
    },
    {
        id: '25645',
        title: 'The Lost Princess of Oz',
        author: 'L. Frank Baum',
        coverUrl: 'https://picsum.photos/300/400?random=279',
        url: 'https://www.gutenberg.org/files/25645/25645-0.txt',
    },
    {
        id: '26631',
        title: 'The Tin Woodman of Oz',
        author: 'L. Frank Baum',
        coverUrl: 'https://picsum.photos/300/400?random=280',
        url: 'https://www.gutenberg.org/files/26631/26631-0.txt',
    },
    {
        id: '26634',
        title: 'The Magic of Oz',
        author: 'L. Frank Baum',
        coverUrl: 'https://picsum.photos/300/400?random=281',
        url: 'https://www.gutenberg.org/files/26634/26634-0.txt',
    },
    {
        id: '26638',
        title: 'Glinda of Oz',
        author: 'L. Frank Baum',
        coverUrl: 'https://picsum.photos/300/400?random=282',
        url: 'https://www.gutenberg.org/files/26638/26638-0.txt',
    },
    {
        id: '232',
        title: 'The History of Tom Jones, a Foundling',
        author: 'Henry Fielding',
        coverUrl: 'https://picsum.photos/300/400?random=283',
        url: 'https://www.gutenberg.org/files/232/232-0.txt',
    },
    {
        id: '522',
        title: 'Clarissa Harlowe; or the History of a Young Lady',
        author: 'Samuel Richardson',
        coverUrl: 'https://picsum.photos/300/400?random=284',
        url: 'https://www.gutenberg.org/files/522/522-0.txt',
    },
    {
        id: '519',
        title: 'Pamela, or Virtue Rewarded',
        author: 'Samuel Richardson',
        coverUrl: 'https://picsum.photos/300/400?random=285',
        url: 'https://www.gutenberg.org/files/519/519-0.txt',
    },
    {
        id: '512',
        title: 'The Life and Opinions of Tristram Shandy, Gentleman',
        author: 'Laurence Sterne',
        coverUrl: 'https://picsum.photos/300/400?random=286',
        url: 'https://www.gutenberg.org/files/512/512-0.txt',
    },
    {
        id: '513',
        title: 'A Sentimental Journey Through France and Italy',
        author: 'Laurence Sterne',
        coverUrl: 'https://picsum.photos/300/400?random=287',
        url: 'https://www.gutenberg.org/files/513/513-0.txt',
    },
    {
        id: '2183',
        title: 'The Expedition of Humphry Clinker',
        author: 'Tobias Smollett',
        coverUrl: 'https://picsum.photos/300/400?random=288',
        url: 'https://www.gutenberg.org/files/2183/2183-0.txt',
    },
    {
        id: '2184',
        title: 'The Adventures of Roderick Random',
        author: 'Tobias Smollett',
        coverUrl: 'https://picsum.photos/300/400?random=289',
        url: 'https://www.gutenberg.org/files/2184/2184-0.txt',
    },
    {
        id: '2185',
        title: 'The Adventures of Peregrine Pickle',
        author: 'Tobias Smollett',
        coverUrl: 'https://picsum.photos/300/400?random=290',
        url: 'https://www.gutenberg.org/files/2185/2185-0.txt',
    },
    {
        id: '541',
        title: 'Vanity Fair',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=291',
        url: 'https://www.gutenberg.org/files/541/541-0.txt',
    },
    {
        id: '542',
        title: 'The History of Pendennis',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=292',
        url: 'https://www.gutenberg.org/files/542/542-0.txt',
    },
    {
        id: '543',
        title: 'The Newcomes',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=293',
        url: 'https://www.gutenberg.org/files/543/543-0.txt',
    },
    {
        id: '544',
        title: 'The History of Henry Esmond, Esq.',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=294',
        url: 'https://www.gutenberg.org/files/544/544-0.txt',
    },
    {
        id: '545',
        title: 'The Virginians',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=295',
        url: 'https://www.gutenberg.org/files/545/545-0.txt',
    },
    {
        id: '547',
        title: 'The Adventures of Philip',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=296',
        url: 'https://www.gutenberg.org/files/547/547-0.txt',
    },
    {
        id: '548',
        title: 'The Memoirs of Barry Lyndon, Esq.',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=297',
        url: 'https://www.gutenberg.org/files/548/548-0.txt',
    },
    {
        id: '549',
        title: 'The Great Hoggarty Diamond',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=298',
        url: 'https://www.gutenberg.org/files/549/549-0.txt',
    },
    {
        id: '550',
        title: 'The Book of Snobs',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=299',
        url: 'https://www.gutenberg.org/files/550/550-0.txt',
    },
    {
        id: '551',
        title: 'The Rose and the Ring',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=300',
        url: 'https://www.gutenberg.org/files/551/551-0.txt',
    },
    {
        id: '552',
        title: 'The Kickleburys on the Rhine',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=301',
        url: 'https://www.gutenberg.org/files/552/552-0.txt',
    },
    {
        id: '553',
        title: 'Rebecca and Rowena',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=302',
        url: 'https://www.gutenberg.org/files/553/553-0.txt',
    },
    {
        id: '554',
        title: 'The History of Samuel Titmarsh and the Great Hoggarty Diamond',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=303',
        url: 'https://www.gutenberg.org/files/554/554-0.txt',
    },
    {
        id: '555',
        title: 'Burlesques',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=304',
        url: 'https://www.gutenberg.org/files/555/555-0.txt',
    },
    {
        id: '556',
        title: 'A Legend of the Rhine',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=305',
        url: 'https://www.gutenberg.org/files/556/556-0.txt',
    },
    {
        id: '557',
        title: 'The Paris Sketch Book of Mr. M. A. Titmarsh',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=306',
        url: 'https://www.gutenberg.org/files/557/557-0.txt',
    },
    {
        id: '558',
        title: 'The Irish Sketch Book',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=307',
        url: 'https://www.gutenberg.org/files/558/558-0.txt',
    },
    {
        id: '559',
        title: 'Notes of a Journey from Cornhill to Grand Cairo',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=308',
        url: 'https://www.gutenberg.org/files/559/559-0.txt',
    },
    {
        id: '560',
        title: 'The Yellowplush Papers',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=309',
        url: 'https://www.gutenberg.org/files/560/560-0.txt',
    },
    {
        id: '561',
        title: 'The Fitz-Boodle Papers',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=310',
        url: 'https://www.gutenberg.org/files/561/561-0.txt',
    },
    {
        id: '562',
        title: 'Men\'s Wives',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=311',
        url: 'https://www.gutenberg.org/files/562/562-0.txt',
    },
    {
        id: '563',
        title: 'The Bedford-Row Conspiracy',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=312',
        url: 'https://www.gutenberg.org/files/563/563-0.txt',
    },
    {
        id: '565',
        title: 'A Little Dinner at Timmins\'s',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=313',
        url: 'https://www.gutenberg.org/files/565/565-0.txt',
    },
    {
        id: '566',
        title: 'The Fatal Boots',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=314',
        url: 'https://www.gutenberg.org/files/566/566-0.txt',
    },
    {
        id: '567',
        title: 'Cox\'s Diary',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=315',
        url: 'https://www.gutenberg.org/files/567/567-0.txt',
    },
    {
        id: '568',
        title: 'The Diary of C. Jeames de la Pluche, Esq. with his letters',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=316',
        url: 'https://www.gutenberg.org/files/568/568-0.txt',
    },
    {
        id: '569',
        title: 'A Legend of the Rhine, and Other Sketches',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=317',
        url: 'https://www.gutenberg.org/files/569/569-0.txt',
    },
    {
        id: '570',
        title: 'Character Sketches',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=318',
        url: 'https://www.gutenberg.org/files/570/570-0.txt',
    },
    {
        id: '571',
        title: 'The Tremendous Adventures of Major Gahagan',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=319',
        url: 'https://www.gutenberg.org/files/571/571-0.txt',
    },
    {
        id: '572',
        title: 'The Wolves and the Lamb',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=320',
        url: 'https://www.gutenberg.org/files/572/572-0.txt',
    },
    {
        id: '573',
        title: 'Lovel the Widower',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=321',
        url: 'https://www.gutenberg.org/files/573/573-0.txt',
    },
    {
        id: '575',
        title: 'Denis Duval',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=322',
        url: 'https://www.gutenberg.org/files/575/575-0.txt',
    },
    {
        id: '576',
        title: 'The Four Georges',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=323',
        url: 'https://www.gutenberg.org/files/576/576-0.txt',
    },
    {
        id: '577',
        title: 'The English Humourists of the Eighteenth Century',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=324',
        url: 'https://www.gutenberg.org/files/577/577-0.txt',
    },
    {
        id: '578',
        title: 'Roundabout Papers',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=325',
        url: 'https://www.gutenberg.org/files/578/578-0.txt',
    },
    {
        id: '579',
        title: 'Critical Reviews',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=326',
        url: 'https://www.gutenberg.org/files/579/579-0.txt',
    },
    {
        id: '581',
        title: 'The Second Funeral of Napoleon',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=327',
        url: 'https://www.gutenberg.org/files/581/581-0.txt',
    },
    {
        id: '582',
        title: 'Sketches and Travels in London',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=328',
        url: 'https://www.gutenberg.org/files/582/582-0.txt',
    },
    {
        id: '583',
        title: 'Catherine: A Story',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=329',
        url: 'https://www.gutenberg.org/files/583/583-0.txt',
    },
    {
        id: '584',
        title: 'The Hoggarty Diamond',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=330',
        url: 'https://www.gutenberg.org/files/584/584-0.txt',
    },
    {
        id: '585',
        title: 'The Amours of Mr. Deuceace',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=331',
        url: 'https://www.gutenberg.org/files/585/585-0.txt',
    },
    {
        id: '586',
        title: 'The History of the Next French Revolution',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=332',
        url: 'https://www.gutenberg.org/files/586/586-0.txt',
    },
    {
        id: '587',
        title: 'The Memoirs of Mr. C. J. Yellowplush',
        author: 'William Makepeace Thackeray',
        coverUrl: 'https://picsum.photos/300/400?random=333',
        url: 'https://www.gutenberg.org/files/587/587-0.txt',
    },
    {
        id: '588',
        title: 'The Diary of a Man of Fifty',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=334',
        url: 'https://www.gutenberg.org/files/588/588-0.txt',
    },
    {
        id: '589',
        title: 'The Europeans',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=335',
        url: 'https://www.gutenberg.org/files/589/589-0.txt',
    },
    {
        id: '206',
        title: 'The Portrait of a Lady',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=336',
        url: 'https://www.gutenberg.org/files/206/206-0.txt',
    },
    {
        id: '207',
        title: 'The Wings of the Dove',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=337',
        url: 'https://www.gutenberg.org/files/207/207-0.txt',
    },
    {
        id: '210',
        title: 'The Ambassadors',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=338',
        url: 'https://www.gutenberg.org/files/210/210-0.txt',
    },
    {
        id: '211',
        title: 'The Golden Bowl',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=339',
        url: 'https://www.gutenberg.org/files/211/211-0.txt',
    },
    {
        id: '212',
        title: 'The American',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=340',
        url: 'https://www.gutenberg.org/files/212/212-0.txt',
    },
    {
        id: '213',
        title: 'The Awkward Age',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=341',
        url: 'https://www.gutenberg.org/files/213/213-0.txt',
    },
    {
        id: '214',
        title: 'The Bostonians',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=342',
        url: 'https://www.gutenberg.org/files/214/214-0.txt',
    },
    {
        id: '216',
        title: 'Confidence',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=343',
        url: 'https://www.gutenberg.org/files/216/216-0.txt',
    },
    {
        id: '218',
        title: 'Daisy Miller: A Study',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=344',
        url: 'https://www.gutenberg.org/files/218/218-0.txt',
    },
    {
        id: '221',
        title: 'The Princess Casamassima',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=345',
        url: 'https://www.gutenberg.org/files/221/221-0.txt',
    },
    {
        id: '222',
        title: 'Roderick Hudson',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=346',
        url: 'https://www.gutenberg.org/files/222/222-0.txt',
    },
    {
        id: '223',
        title: 'The Sacred Fount',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=347',
        url: 'https://www.gutenberg.org/files/223/223-0.txt',
    },
    {
        id: '224',
        title: 'The Spoils of Poynton',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=348',
        url: 'https://www.gutenberg.org/files/224/224-0.txt',
    },
    {
        id: '225',
        title: 'The Tragic Muse',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=349',
        url: 'https://www.gutenberg.org/files/225/225-0.txt',
    },
    {
        id: '226',
        title: 'Washington Square',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=350',
        url: 'https://www.gutenberg.org/files/226/226-0.txt',
    },
    {
        id: '227',
        title: 'What Maisie Knew',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=351',
        url: 'https://www.gutenberg.org/files/227/227-0.txt',
    },
    {
        id: '229',
        title: 'The Altar of the Dead',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=352',
        url: 'https://www.gutenberg.org/files/229/229-0.txt',
    },
    {
        id: '230',
        title: 'The Aspern Papers',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=353',
        url: 'https://www.gutenberg.org/files/230/230-0.txt',
    },
    {
        id: '231',
        title: 'The Author of Beltraffio',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=354',
        url: 'https://www.gutenberg.org/files/231/231-0.txt',
    },
    {
        id: '233',
        title: 'The Beast in the Jungle',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=355',
        url: 'https://www.gutenberg.org/files/233/233-0.txt',
    },
    {
        id: '234',
        title: 'The Birthplace',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=356',
        url: 'https://www.gutenberg.org/files/234/234-0.txt',
    },
    {
        id: '235',
        title: 'The Coxon Fund',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=357',
        url: 'https://www.gutenberg.org/files/235/235-0.txt',
    },
    {
        id: '236',
        title: 'The Death of the Lion',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=358',
        url: 'https://www.gutenberg.org/files/236/236-0.txt',
    },
    {
        id: '237',
        title: 'The Figure in the Carpet',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=359',
        url: 'https://www.gutenberg.org/files/237/237-0.txt',
    },
    {
        id: '238',
        title: 'The Friends of the Friends',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=360',
        url: 'https://www.gutenberg.org/files/238/238-0.txt',
    },
    {
        id: '239',
        title: 'The Glasses',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=361',
        url: 'https://www.gutenberg.org/files/239/239-0.txt',
    },
    {
        id: '240',
        title: 'The Jolly Corner',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=362',
        url: 'https://www.gutenberg.org/files/240/240-0.txt',
    },
    {
        id: '241',
        title: 'The Lesson of the Master',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=363',
        url: 'https://www.gutenberg.org/files/241/241-0.txt',
    },
    {
        id: '242',
        title: 'The Liar',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=364',
        url: 'https://www.gutenberg.org/files/242/242-0.txt',
    },
    {
        id: '243',
        title: 'The Middle Years',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=365',
        url: 'https://www.gutenberg.org/files/243/243-0.txt',
    },
    {
        id: '246',
        title: 'The Next Time',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=366',
        url: 'https://www.gutenberg.org/files/246/246-0.txt',
    },
    {
        id: '247',
        title: 'The Papers',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=367',
        url: 'https://www.gutenberg.org/files/247/247-0.txt',
    },
    {
        id: '248',
        title: 'The Patagonia',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=368',
        url: 'https://www.gutenberg.org/files/248/248-0.txt',
    },
    {
        id: '249',
        title: 'The Pupil',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=369',
        url: 'https://www.gutenberg.org/files/249/249-0.txt',
    },
    {
        id: '250',
        title: 'The Real Thing',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=370',
        url: 'https://www.gutenberg.org/files/250/250-0.txt',
    },
    {
        id: '251',
        title: 'The Reverberator',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=371',
        url: 'https://www.gutenberg.org/files/251/251-0.txt',
    },
    {
        id: '252',
        title: 'The Siege of London',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=372',
        url: 'https://www.gutenberg.org/files/252/252-0.txt',
    },
    {
        id: '253',
        title: 'The Solution',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=373',
        url: 'https://www.gutenberg.org/files/253/253-0.txt',
    },
    {
        id: '254',
        title: 'The Story of a Year',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=374',
        url: 'https://www.gutenberg.org/files/254/254-0.txt',
    },
    {
        id: '255',
        title: 'The Third Person',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=375',
        url: 'https://www.gutenberg.org/files/255/255-0.txt',
    },
    {
        id: '256',
        title: 'The Two Faces',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=376',
        url: 'https://www.gutenberg.org/files/256/256-0.txt',
    },
    {
        id: '257',
        title: 'The Velvet Glove',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=377',
        url: 'https://www.gutenberg.org/files/257/257-0.txt',
    },
    {
        id: '258',
        title: 'The Way It Came',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=378',
        url: 'https://www.gutenberg.org/files/258/258-0.txt',
    },
    {
        id: '259',
        title: 'The Wheel of Time',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=379',
        url: 'https://www.gutenberg.org/files/259/259-0.txt',
    },
    {
        id: '260',
        title: 'A Bundle of Letters',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=380',
        url: 'https://www.gutenberg.org/files/260/260-0.txt',
    },
    {
        id: '261',
        title: 'A Day of Days',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=381',
        url: 'https://www.gutenberg.org/files/261/261-0.txt',
    },
    {
        id: '262',
        title: 'A Landscape Painter',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=382',
        url: 'https://www.gutenberg.org/files/262/262-0.txt',
    },
    {
        id: '263',
        title: 'A Light Man',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=383',
        url: 'https://www.gutenberg.org/files/263/263-0.txt',
    },
    {
        id: '264',
        title: 'A London Life',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=384',
        url: 'https://www.gutenberg.org/files/264/264-0.txt',
    },
    {
        id: '265',
        title: 'A Most Extraordinary Case',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=385',
        url: 'https://www.gutenberg.org/files/265/265-0.txt',
    },
    {
        id: '266',
        title: 'A Passionate Pilgrim',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=386',
        url: 'https://www.gutenberg.org/files/266/266-0.txt',
    },
    {
        id: '267',
        title: 'An International Episode',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=387',
        url: 'https://www.gutenberg.org/files/267/267-0.txt',
    },
    {
        id: '268',
        title: 'At Isella',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=388',
        url: 'https://www.gutenberg.org/files/268/268-0.txt',
    },
    {
        id: '269',
        title: 'Benvolio',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=389',
        url: 'https://www.gutenberg.org/files/269/269-0.txt',
    },
    {
        id: '270',
        title: 'Collaboration',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=390',
        url: 'https://www.gutenberg.org/files/270/270-0.txt',
    },
    {
        id: '271',
        title: 'Crawford\'s Consistency',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=391',
        url: 'https://www.gutenberg.org/files/271/271-0.txt',
    },
    {
        id: '272',
        title: 'Eugene Pickering',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=392',
        url: 'https://www.gutenberg.org/files/272/272-0.txt',
    },
    {
        id: '273',
        title: 'Europe',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=393',
        url: 'https://www.gutenberg.org/files/273/273-0.txt',
    },
    {
        id: '274',
        title: 'Fordham Castle',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=394',
        url: 'https://www.gutenberg.org/files/274/274-0.txt',
    },
    {
        id: '275',
        title: 'Four Meetings',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=395',
        url: 'https://www.gutenberg.org/files/275/275-0.txt',
    },
    {
        id: '276',
        title: 'Gabrielle de Bergerac',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=396',
        url: 'https://www.gutenberg.org/files/276/276-0.txt',
    },
    {
        id: '277',
        title: 'Georgina\'s Reasons',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=397',
        url: 'https://www.gutenberg.org/files/277/277-0.txt',
    },
    {
        id: '278',
        title: 'Guest\'s Confession',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=398',
        url: 'https://www.gutenberg.org/files/278/278-0.txt',
    },
    {
        id: '279',
        title: 'Impressions of a Cousin',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=399',
        url: 'https://www.gutenberg.org/files/279/279-0.txt',
    },
    {
        id: '280',
        title: 'In the Cage',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=400',
        url: 'https://www.gutenberg.org/files/280/280-0.txt',
    },
    {
        id: '281',
        title: 'John Delavoy',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=401',
        url: 'https://www.gutenberg.org/files/281/281-0.txt',
    },
    {
        id: '282',
        title: 'Julia Bride',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=402',
        url: 'https://www.gutenberg.org/files/282/282-0.txt',
    },
    {
        id: '283',
        title: 'Lady Barbarina',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=403',
        url: 'https://www.gutenberg.org/files/283/283-0.txt',
    },
    {
        id: '284',
        title: 'Longstaff\'s Marriage',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=404',
        url: 'https://www.gutenberg.org/files/284/284-0.txt',
    },
    {
        id: '285',
        title: 'Lord Beaupré',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=405',
        url: 'https://www.gutenberg.org/files/285/285-0.txt',
    },
    {
        id: '286',
        title: 'Louisa Pallant',
        author: 'Henry James',
        coverUrl: 'https://picsum.photos/300/400?random=406',
        url: 'https://www.gutenberg.org/files/286/286-0.txt',
    }
];
